namespace POS_Shop.Views.Controllers.City
{
    partial class CityControl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CityControl));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.CityNameTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.SaveCityBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.CountryDatagridView = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.CountryDropDownLst = new Bunifu.UI.WinForms.BunifuDropdown();
            this.label3 = new System.Windows.Forms.Label();
            this.lblCityName = new System.Windows.Forms.Label();
            this.cityIdTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.UpdateCitybtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.PrintBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.CityPrintPreviewDialog = new System.Windows.Forms.PrintPreviewDialog();
            this.CityPrintDocument = new System.Drawing.Printing.PrintDocument();
            this.panel1 = new System.Windows.Forms.Panel();
            this.cityGrdiheadingLbl = new System.Windows.Forms.Label();
            this.SearchCityTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.SearchCityBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.PrevBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.NextBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel2 = new System.Windows.Forms.Panel();
            ((System.ComponentModel.ISupportInitialize)(this.CountryDatagridView)).BeginInit();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // CityNameTxt
            // 
            this.CityNameTxt.AcceptsReturn = false;
            this.CityNameTxt.AcceptsTab = false;
            this.CityNameTxt.AnimationSpeed = 200;
            this.CityNameTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.CityNameTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.CityNameTxt.BackColor = System.Drawing.Color.Transparent;
            this.CityNameTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CityNameTxt.BackgroundImage")));
            this.CityNameTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.CityNameTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CityNameTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CityNameTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.CityNameTxt.BorderRadius = 2;
            this.CityNameTxt.BorderThickness = 1;
            this.CityNameTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.CityNameTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.CityNameTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.CityNameTxt.DefaultText = "";
            this.CityNameTxt.FillColor = System.Drawing.Color.White;
            this.CityNameTxt.HideSelection = true;
            this.CityNameTxt.IconLeft = null;
            this.CityNameTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.CityNameTxt.IconPadding = 10;
            this.CityNameTxt.IconRight = null;
            this.CityNameTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.CityNameTxt.Lines = new string[0];
            this.CityNameTxt.Location = new System.Drawing.Point(108, 18);
            this.CityNameTxt.MaxLength = 32767;
            this.CityNameTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.CityNameTxt.Modified = false;
            this.CityNameTxt.Multiline = false;
            this.CityNameTxt.Name = "CityNameTxt";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CityNameTxt.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.CityNameTxt.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CityNameTxt.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CityNameTxt.OnIdleState = stateProperties4;
            this.CityNameTxt.Padding = new System.Windows.Forms.Padding(3);
            this.CityNameTxt.PasswordChar = '\0';
            this.CityNameTxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.CityNameTxt.PlaceholderText = "Enter text";
            this.CityNameTxt.ReadOnly = false;
            this.CityNameTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.CityNameTxt.SelectedText = "";
            this.CityNameTxt.SelectionLength = 0;
            this.CityNameTxt.SelectionStart = 0;
            this.CityNameTxt.ShortcutsEnabled = true;
            this.CityNameTxt.Size = new System.Drawing.Size(342, 41);
            this.CityNameTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.CityNameTxt.TabIndex = 1;
            this.CityNameTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.CityNameTxt.TextMarginBottom = 0;
            this.CityNameTxt.TextMarginLeft = 3;
            this.CityNameTxt.TextMarginTop = 0;
            this.CityNameTxt.TextPlaceholder = "Enter text";
            this.CityNameTxt.UseSystemPasswordChar = false;
            this.CityNameTxt.WordWrap = true;
            // 
            // SaveCityBtn
            // 
            this.SaveCityBtn.AllowAnimations = true;
            this.SaveCityBtn.AllowMouseEffects = true;
            this.SaveCityBtn.AllowToggling = false;
            this.SaveCityBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.SaveCityBtn.AnimationSpeed = 200;
            this.SaveCityBtn.AutoGenerateColors = false;
            this.SaveCityBtn.AutoRoundBorders = false;
            this.SaveCityBtn.AutoSizeLeftIcon = true;
            this.SaveCityBtn.AutoSizeRightIcon = true;
            this.SaveCityBtn.BackColor = System.Drawing.Color.Transparent;
            this.SaveCityBtn.BackColor1 = System.Drawing.Color.SlateBlue;
            this.SaveCityBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("SaveCityBtn.BackgroundImage")));
            this.SaveCityBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SaveCityBtn.ButtonText = "Save";
            this.SaveCityBtn.ButtonTextMarginLeft = 0;
            this.SaveCityBtn.ColorContrastOnClick = 45;
            this.SaveCityBtn.ColorContrastOnHover = 45;
            this.SaveCityBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.SaveCityBtn.CustomizableEdges = borderEdges1;
            this.SaveCityBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.SaveCityBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.SaveCityBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SaveCityBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.SaveCityBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.SaveCityBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.SaveCityBtn.ForeColor = System.Drawing.Color.White;
            this.SaveCityBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.SaveCityBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.SaveCityBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.SaveCityBtn.IconMarginLeft = 11;
            this.SaveCityBtn.IconPadding = 10;
            this.SaveCityBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.SaveCityBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.SaveCityBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.SaveCityBtn.IconSize = 25;
            this.SaveCityBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.SaveCityBtn.IdleBorderRadius = 1;
            this.SaveCityBtn.IdleBorderThickness = 1;
            this.SaveCityBtn.IdleFillColor = System.Drawing.Color.SlateBlue;
            this.SaveCityBtn.IdleIconLeftImage = null;
            this.SaveCityBtn.IdleIconRightImage = null;
            this.SaveCityBtn.IndicateFocus = false;
            this.SaveCityBtn.Location = new System.Drawing.Point(1008, 95);
            this.SaveCityBtn.Name = "SaveCityBtn";
            this.SaveCityBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.SaveCityBtn.OnDisabledState.BorderRadius = 1;
            this.SaveCityBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SaveCityBtn.OnDisabledState.BorderThickness = 1;
            this.SaveCityBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SaveCityBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.SaveCityBtn.OnDisabledState.IconLeftImage = null;
            this.SaveCityBtn.OnDisabledState.IconRightImage = null;
            this.SaveCityBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.SaveCityBtn.onHoverState.BorderRadius = 1;
            this.SaveCityBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SaveCityBtn.onHoverState.BorderThickness = 1;
            this.SaveCityBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.SaveCityBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.SaveCityBtn.onHoverState.IconLeftImage = null;
            this.SaveCityBtn.onHoverState.IconRightImage = null;
            this.SaveCityBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.SaveCityBtn.OnIdleState.BorderRadius = 1;
            this.SaveCityBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SaveCityBtn.OnIdleState.BorderThickness = 1;
            this.SaveCityBtn.OnIdleState.FillColor = System.Drawing.Color.SlateBlue;
            this.SaveCityBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.SaveCityBtn.OnIdleState.IconLeftImage = null;
            this.SaveCityBtn.OnIdleState.IconRightImage = null;
            this.SaveCityBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.SaveCityBtn.OnPressedState.BorderRadius = 1;
            this.SaveCityBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SaveCityBtn.OnPressedState.BorderThickness = 1;
            this.SaveCityBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.SaveCityBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.SaveCityBtn.OnPressedState.IconLeftImage = null;
            this.SaveCityBtn.OnPressedState.IconRightImage = null;
            this.SaveCityBtn.Size = new System.Drawing.Size(150, 39);
            this.SaveCityBtn.TabIndex = 3;
            this.SaveCityBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.SaveCityBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.SaveCityBtn.TextMarginLeft = 0;
            this.SaveCityBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.SaveCityBtn.UseDefaultRadiusAndThickness = true;
            this.SaveCityBtn.Click += new System.EventHandler(this.SaveCityBtn_Click);
            // 
            // CountryDatagridView
            // 
            this.CountryDatagridView.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.CountryDatagridView.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.CountryDatagridView.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.CountryDatagridView.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.CountryDatagridView.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.CountryDatagridView.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.CountryDatagridView.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.CountryDatagridView.ColumnHeadersHeight = 40;
            this.CountryDatagridView.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.CountryDatagridView.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.CountryDatagridView.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.CountryDatagridView.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.CountryDatagridView.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.CountryDatagridView.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.CountryDatagridView.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.CountryDatagridView.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.CountryDatagridView.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.CountryDatagridView.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.CountryDatagridView.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.CountryDatagridView.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.CountryDatagridView.CurrentTheme.Name = null;
            this.CountryDatagridView.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.CountryDatagridView.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.CountryDatagridView.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.CountryDatagridView.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.CountryDatagridView.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.CountryDatagridView.DefaultCellStyle = dataGridViewCellStyle3;
            this.CountryDatagridView.EnableHeadersVisualStyles = false;
            this.CountryDatagridView.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.CountryDatagridView.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.CountryDatagridView.HeaderBgColor = System.Drawing.Color.Empty;
            this.CountryDatagridView.HeaderForeColor = System.Drawing.Color.White;
            this.CountryDatagridView.Location = new System.Drawing.Point(17, 274);
            this.CountryDatagridView.Name = "CountryDatagridView";
            this.CountryDatagridView.RowHeadersVisible = false;
            this.CountryDatagridView.RowHeadersWidth = 51;
            this.CountryDatagridView.RowTemplate.Height = 40;
            this.CountryDatagridView.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.CountryDatagridView.Size = new System.Drawing.Size(1156, 328);
            this.CountryDatagridView.TabIndex = 3;
            this.CountryDatagridView.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.CountryDatagridView.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.CountryDatagridView_CellClick);
            // 
            // CountryDropDownLst
            // 
            this.CountryDropDownLst.BackColor = System.Drawing.Color.Transparent;
            this.CountryDropDownLst.BackgroundColor = System.Drawing.Color.White;
            this.CountryDropDownLst.BorderColor = System.Drawing.Color.Silver;
            this.CountryDropDownLst.BorderRadius = 1;
            this.CountryDropDownLst.Color = System.Drawing.Color.Silver;
            this.CountryDropDownLst.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.CountryDropDownLst.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.CountryDropDownLst.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CountryDropDownLst.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.CountryDropDownLst.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.CountryDropDownLst.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.CountryDropDownLst.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.CountryDropDownLst.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.CountryDropDownLst.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.CountryDropDownLst.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.CountryDropDownLst.FillDropDown = true;
            this.CountryDropDownLst.FillIndicator = false;
            this.CountryDropDownLst.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.CountryDropDownLst.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.CountryDropDownLst.ForeColor = System.Drawing.Color.Black;
            this.CountryDropDownLst.FormattingEnabled = true;
            this.CountryDropDownLst.Icon = null;
            this.CountryDropDownLst.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.CountryDropDownLst.IndicatorColor = System.Drawing.Color.Gray;
            this.CountryDropDownLst.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.CountryDropDownLst.ItemBackColor = System.Drawing.Color.White;
            this.CountryDropDownLst.ItemBorderColor = System.Drawing.Color.White;
            this.CountryDropDownLst.ItemForeColor = System.Drawing.Color.Black;
            this.CountryDropDownLst.ItemHeight = 29;
            this.CountryDropDownLst.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.CountryDropDownLst.ItemHighLightForeColor = System.Drawing.Color.White;
            this.CountryDropDownLst.ItemTopMargin = 3;
            this.CountryDropDownLst.Location = new System.Drawing.Point(634, 20);
            this.CountryDropDownLst.Name = "CountryDropDownLst";
            this.CountryDropDownLst.Size = new System.Drawing.Size(260, 35);
            this.CountryDropDownLst.TabIndex = 2;
            this.CountryDropDownLst.Text = null;
            this.CountryDropDownLst.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.CountryDropDownLst.TextLeftMargin = 2;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(472, 29);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(119, 18);
            this.label3.TabIndex = 5;
            this.label3.Text = "Select Country";
            // 
            // lblCityName
            // 
            this.lblCityName.AutoSize = true;
            this.lblCityName.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCityName.Location = new System.Drawing.Point(10, 23);
            this.lblCityName.Name = "lblCityName";
            this.lblCityName.Size = new System.Drawing.Size(86, 18);
            this.lblCityName.TabIndex = 0;
            this.lblCityName.Text = "City Name";
            // 
            // cityIdTxt
            // 
            this.cityIdTxt.AcceptsReturn = false;
            this.cityIdTxt.AcceptsTab = false;
            this.cityIdTxt.AnimationSpeed = 200;
            this.cityIdTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.cityIdTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.cityIdTxt.BackColor = System.Drawing.Color.Transparent;
            this.cityIdTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cityIdTxt.BackgroundImage")));
            this.cityIdTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.cityIdTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cityIdTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cityIdTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.cityIdTxt.BorderRadius = 1;
            this.cityIdTxt.BorderThickness = 1;
            this.cityIdTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.cityIdTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.cityIdTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.cityIdTxt.DefaultText = "";
            this.cityIdTxt.FillColor = System.Drawing.Color.White;
            this.cityIdTxt.HideSelection = true;
            this.cityIdTxt.IconLeft = null;
            this.cityIdTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.cityIdTxt.IconPadding = 10;
            this.cityIdTxt.IconRight = null;
            this.cityIdTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.cityIdTxt.Lines = new string[0];
            this.cityIdTxt.Location = new System.Drawing.Point(109, 65);
            this.cityIdTxt.MaxLength = 32767;
            this.cityIdTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.cityIdTxt.Modified = false;
            this.cityIdTxt.Multiline = false;
            this.cityIdTxt.Name = "cityIdTxt";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cityIdTxt.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.cityIdTxt.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cityIdTxt.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cityIdTxt.OnIdleState = stateProperties8;
            this.cityIdTxt.Padding = new System.Windows.Forms.Padding(3);
            this.cityIdTxt.PasswordChar = '\0';
            this.cityIdTxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.cityIdTxt.PlaceholderText = "Enter text";
            this.cityIdTxt.ReadOnly = false;
            this.cityIdTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.cityIdTxt.SelectedText = "";
            this.cityIdTxt.SelectionLength = 0;
            this.cityIdTxt.SelectionStart = 0;
            this.cityIdTxt.ShortcutsEnabled = true;
            this.cityIdTxt.Size = new System.Drawing.Size(101, 25);
            this.cityIdTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.cityIdTxt.TabIndex = 6;
            this.cityIdTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.cityIdTxt.TextMarginBottom = 0;
            this.cityIdTxt.TextMarginLeft = 3;
            this.cityIdTxt.TextMarginTop = 0;
            this.cityIdTxt.TextPlaceholder = "Enter text";
            this.cityIdTxt.UseSystemPasswordChar = false;
            this.cityIdTxt.Visible = false;
            this.cityIdTxt.WordWrap = true;
            // 
            // UpdateCitybtn
            // 
            this.UpdateCitybtn.AllowAnimations = true;
            this.UpdateCitybtn.AllowMouseEffects = true;
            this.UpdateCitybtn.AllowToggling = false;
            this.UpdateCitybtn.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.UpdateCitybtn.AnimationSpeed = 200;
            this.UpdateCitybtn.AutoGenerateColors = false;
            this.UpdateCitybtn.AutoRoundBorders = false;
            this.UpdateCitybtn.AutoSizeLeftIcon = true;
            this.UpdateCitybtn.AutoSizeRightIcon = true;
            this.UpdateCitybtn.BackColor = System.Drawing.Color.Transparent;
            this.UpdateCitybtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.UpdateCitybtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("UpdateCitybtn.BackgroundImage")));
            this.UpdateCitybtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UpdateCitybtn.ButtonText = "Update";
            this.UpdateCitybtn.ButtonTextMarginLeft = 0;
            this.UpdateCitybtn.ColorContrastOnClick = 45;
            this.UpdateCitybtn.ColorContrastOnHover = 45;
            this.UpdateCitybtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.UpdateCitybtn.CustomizableEdges = borderEdges2;
            this.UpdateCitybtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.UpdateCitybtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.UpdateCitybtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UpdateCitybtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.UpdateCitybtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.UpdateCitybtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.UpdateCitybtn.ForeColor = System.Drawing.Color.White;
            this.UpdateCitybtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.UpdateCitybtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.UpdateCitybtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.UpdateCitybtn.IconMarginLeft = 11;
            this.UpdateCitybtn.IconPadding = 10;
            this.UpdateCitybtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.UpdateCitybtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.UpdateCitybtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.UpdateCitybtn.IconSize = 25;
            this.UpdateCitybtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.UpdateCitybtn.IdleBorderRadius = 1;
            this.UpdateCitybtn.IdleBorderThickness = 1;
            this.UpdateCitybtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.UpdateCitybtn.IdleIconLeftImage = null;
            this.UpdateCitybtn.IdleIconRightImage = null;
            this.UpdateCitybtn.IndicateFocus = false;
            this.UpdateCitybtn.Location = new System.Drawing.Point(852, 94);
            this.UpdateCitybtn.Name = "UpdateCitybtn";
            this.UpdateCitybtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.UpdateCitybtn.OnDisabledState.BorderRadius = 1;
            this.UpdateCitybtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UpdateCitybtn.OnDisabledState.BorderThickness = 1;
            this.UpdateCitybtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UpdateCitybtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.UpdateCitybtn.OnDisabledState.IconLeftImage = null;
            this.UpdateCitybtn.OnDisabledState.IconRightImage = null;
            this.UpdateCitybtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.UpdateCitybtn.onHoverState.BorderRadius = 1;
            this.UpdateCitybtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UpdateCitybtn.onHoverState.BorderThickness = 1;
            this.UpdateCitybtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.UpdateCitybtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.UpdateCitybtn.onHoverState.IconLeftImage = null;
            this.UpdateCitybtn.onHoverState.IconRightImage = null;
            this.UpdateCitybtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.UpdateCitybtn.OnIdleState.BorderRadius = 1;
            this.UpdateCitybtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UpdateCitybtn.OnIdleState.BorderThickness = 1;
            this.UpdateCitybtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.UpdateCitybtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.UpdateCitybtn.OnIdleState.IconLeftImage = null;
            this.UpdateCitybtn.OnIdleState.IconRightImage = null;
            this.UpdateCitybtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.UpdateCitybtn.OnPressedState.BorderRadius = 1;
            this.UpdateCitybtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UpdateCitybtn.OnPressedState.BorderThickness = 1;
            this.UpdateCitybtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.UpdateCitybtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.UpdateCitybtn.OnPressedState.IconLeftImage = null;
            this.UpdateCitybtn.OnPressedState.IconRightImage = null;
            this.UpdateCitybtn.Size = new System.Drawing.Size(150, 39);
            this.UpdateCitybtn.TabIndex = 4;
            this.UpdateCitybtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.UpdateCitybtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.UpdateCitybtn.TextMarginLeft = 0;
            this.UpdateCitybtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.UpdateCitybtn.UseDefaultRadiusAndThickness = true;
            this.UpdateCitybtn.Visible = false;
            this.UpdateCitybtn.Click += new System.EventHandler(this.UpdateCitybtn_Click);
            // 
            // PrintBtn
            // 
            this.PrintBtn.AllowAnimations = true;
            this.PrintBtn.AllowMouseEffects = true;
            this.PrintBtn.AllowToggling = false;
            this.PrintBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.PrintBtn.AnimationSpeed = 200;
            this.PrintBtn.AutoGenerateColors = false;
            this.PrintBtn.AutoRoundBorders = false;
            this.PrintBtn.AutoSizeLeftIcon = true;
            this.PrintBtn.AutoSizeRightIcon = true;
            this.PrintBtn.BackColor = System.Drawing.Color.Transparent;
            this.PrintBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.PrintBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PrintBtn.BackgroundImage")));
            this.PrintBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PrintBtn.ButtonText = "Print";
            this.PrintBtn.ButtonTextMarginLeft = 0;
            this.PrintBtn.ColorContrastOnClick = 45;
            this.PrintBtn.ColorContrastOnHover = 45;
            this.PrintBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.PrintBtn.CustomizableEdges = borderEdges3;
            this.PrintBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.PrintBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.PrintBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PrintBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.PrintBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.PrintBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.PrintBtn.ForeColor = System.Drawing.Color.White;
            this.PrintBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.PrintBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.PrintBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.PrintBtn.IconMarginLeft = 11;
            this.PrintBtn.IconPadding = 10;
            this.PrintBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.PrintBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.PrintBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.PrintBtn.IconSize = 25;
            this.PrintBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.PrintBtn.IdleBorderRadius = 1;
            this.PrintBtn.IdleBorderThickness = 1;
            this.PrintBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.PrintBtn.IdleIconLeftImage = null;
            this.PrintBtn.IdleIconRightImage = null;
            this.PrintBtn.IndicateFocus = false;
            this.PrintBtn.Location = new System.Drawing.Point(588, 94);
            this.PrintBtn.Name = "PrintBtn";
            this.PrintBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.PrintBtn.OnDisabledState.BorderRadius = 1;
            this.PrintBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PrintBtn.OnDisabledState.BorderThickness = 1;
            this.PrintBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PrintBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.PrintBtn.OnDisabledState.IconLeftImage = null;
            this.PrintBtn.OnDisabledState.IconRightImage = null;
            this.PrintBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PrintBtn.onHoverState.BorderRadius = 1;
            this.PrintBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PrintBtn.onHoverState.BorderThickness = 1;
            this.PrintBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PrintBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.PrintBtn.onHoverState.IconLeftImage = null;
            this.PrintBtn.onHoverState.IconRightImage = null;
            this.PrintBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.PrintBtn.OnIdleState.BorderRadius = 1;
            this.PrintBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PrintBtn.OnIdleState.BorderThickness = 1;
            this.PrintBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.PrintBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.PrintBtn.OnIdleState.IconLeftImage = null;
            this.PrintBtn.OnIdleState.IconRightImage = null;
            this.PrintBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.PrintBtn.OnPressedState.BorderRadius = 1;
            this.PrintBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PrintBtn.OnPressedState.BorderThickness = 1;
            this.PrintBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.PrintBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.PrintBtn.OnPressedState.IconLeftImage = null;
            this.PrintBtn.OnPressedState.IconRightImage = null;
            this.PrintBtn.Size = new System.Drawing.Size(258, 39);
            this.PrintBtn.TabIndex = 7;
            this.PrintBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.PrintBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.PrintBtn.TextMarginLeft = 0;
            this.PrintBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.PrintBtn.UseDefaultRadiusAndThickness = true;
            this.PrintBtn.Click += new System.EventHandler(this.PrintBtn_Click);
            // 
            // CityPrintPreviewDialog
            // 
            this.CityPrintPreviewDialog.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.CityPrintPreviewDialog.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.CityPrintPreviewDialog.ClientSize = new System.Drawing.Size(400, 300);
            this.CityPrintPreviewDialog.Enabled = true;
            this.CityPrintPreviewDialog.Icon = ((System.Drawing.Icon)(resources.GetObject("CityPrintPreviewDialog.Icon")));
            this.CityPrintPreviewDialog.Name = "CityPrintPreviewDialog";
            this.CityPrintPreviewDialog.Visible = false;
            // 
            // CityPrintDocument
            // 
            this.CityPrintDocument.PrintPage += new System.Drawing.Printing.PrintPageEventHandler(this.CityPrintDocument_PrintPage);
            // 
            // panel1
            // 
            this.panel1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panel1.AutoSize = true;
            this.panel1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panel1.Controls.Add(this.CityNameTxt);
            this.panel1.Controls.Add(this.PrintBtn);
            this.panel1.Controls.Add(this.label3);
            this.panel1.Controls.Add(this.UpdateCitybtn);
            this.panel1.Controls.Add(this.lblCityName);
            this.panel1.Controls.Add(this.CountryDropDownLst);
            this.panel1.Controls.Add(this.SaveCityBtn);
            this.panel1.Controls.Add(this.cityIdTxt);
            this.panel1.Location = new System.Drawing.Point(17, 64);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1163, 139);
            this.panel1.TabIndex = 8;
            // 
            // cityGrdiheadingLbl
            // 
            this.cityGrdiheadingLbl.AutoSize = true;
            this.cityGrdiheadingLbl.Font = new System.Drawing.Font("Ravie", 12F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cityGrdiheadingLbl.ForeColor = System.Drawing.Color.SlateBlue;
            this.cityGrdiheadingLbl.Location = new System.Drawing.Point(154, 19);
            this.cityGrdiheadingLbl.Name = "cityGrdiheadingLbl";
            this.cityGrdiheadingLbl.Size = new System.Drawing.Size(266, 27);
            this.cityGrdiheadingLbl.TabIndex = 10;
            this.cityGrdiheadingLbl.Text = "City Form and List";
            // 
            // SearchCityTxt
            // 
            this.SearchCityTxt.AcceptsReturn = false;
            this.SearchCityTxt.AcceptsTab = false;
            this.SearchCityTxt.AnimationSpeed = 200;
            this.SearchCityTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.SearchCityTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.SearchCityTxt.BackColor = System.Drawing.Color.Transparent;
            this.SearchCityTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("SearchCityTxt.BackgroundImage")));
            this.SearchCityTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.SearchCityTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SearchCityTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.SearchCityTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.SearchCityTxt.BorderRadius = 1;
            this.SearchCityTxt.BorderThickness = 1;
            this.SearchCityTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.SearchCityTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.SearchCityTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.SearchCityTxt.DefaultText = "";
            this.SearchCityTxt.FillColor = System.Drawing.Color.White;
            this.SearchCityTxt.HideSelection = true;
            this.SearchCityTxt.IconLeft = null;
            this.SearchCityTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.SearchCityTxt.IconPadding = 10;
            this.SearchCityTxt.IconRight = null;
            this.SearchCityTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.SearchCityTxt.Lines = new string[0];
            this.SearchCityTxt.Location = new System.Drawing.Point(17, 213);
            this.SearchCityTxt.MaxLength = 32767;
            this.SearchCityTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.SearchCityTxt.Modified = false;
            this.SearchCityTxt.Multiline = false;
            this.SearchCityTxt.Name = "SearchCityTxt";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.SearchCityTxt.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.SearchCityTxt.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.SearchCityTxt.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.SearchCityTxt.OnIdleState = stateProperties12;
            this.SearchCityTxt.Padding = new System.Windows.Forms.Padding(3);
            this.SearchCityTxt.PasswordChar = '\0';
            this.SearchCityTxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.SearchCityTxt.PlaceholderText = "Search City";
            this.SearchCityTxt.ReadOnly = false;
            this.SearchCityTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.SearchCityTxt.SelectedText = "";
            this.SearchCityTxt.SelectionLength = 0;
            this.SearchCityTxt.SelectionStart = 0;
            this.SearchCityTxt.ShortcutsEnabled = true;
            this.SearchCityTxt.Size = new System.Drawing.Size(554, 41);
            this.SearchCityTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.SearchCityTxt.TabIndex = 11;
            this.SearchCityTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.SearchCityTxt.TextMarginBottom = 0;
            this.SearchCityTxt.TextMarginLeft = 3;
            this.SearchCityTxt.TextMarginTop = 0;
            this.SearchCityTxt.TextPlaceholder = "Search City";
            this.SearchCityTxt.UseSystemPasswordChar = false;
            this.SearchCityTxt.WordWrap = true;
            this.SearchCityTxt.TextChange += new System.EventHandler(this.SearchCity_TextChanged);
            // 
            // SearchCityBtn
            // 
            this.SearchCityBtn.AllowAnimations = true;
            this.SearchCityBtn.AllowMouseEffects = true;
            this.SearchCityBtn.AllowToggling = false;
            this.SearchCityBtn.AnimationSpeed = 200;
            this.SearchCityBtn.AutoGenerateColors = false;
            this.SearchCityBtn.AutoRoundBorders = false;
            this.SearchCityBtn.AutoSizeLeftIcon = true;
            this.SearchCityBtn.AutoSizeRightIcon = true;
            this.SearchCityBtn.BackColor = System.Drawing.Color.Transparent;
            this.SearchCityBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.SearchCityBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("SearchCityBtn.BackgroundImage")));
            this.SearchCityBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SearchCityBtn.ButtonText = "Search";
            this.SearchCityBtn.ButtonTextMarginLeft = 0;
            this.SearchCityBtn.ColorContrastOnClick = 45;
            this.SearchCityBtn.ColorContrastOnHover = 45;
            this.SearchCityBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.SearchCityBtn.CustomizableEdges = borderEdges4;
            this.SearchCityBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.SearchCityBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.SearchCityBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SearchCityBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.SearchCityBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.SearchCityBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.SearchCityBtn.ForeColor = System.Drawing.Color.White;
            this.SearchCityBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.SearchCityBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.SearchCityBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.SearchCityBtn.IconMarginLeft = 11;
            this.SearchCityBtn.IconPadding = 10;
            this.SearchCityBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.SearchCityBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.SearchCityBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.SearchCityBtn.IconSize = 25;
            this.SearchCityBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.SearchCityBtn.IdleBorderRadius = 1;
            this.SearchCityBtn.IdleBorderThickness = 1;
            this.SearchCityBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.SearchCityBtn.IdleIconLeftImage = null;
            this.SearchCityBtn.IdleIconRightImage = null;
            this.SearchCityBtn.IndicateFocus = false;
            this.SearchCityBtn.Location = new System.Drawing.Point(577, 213);
            this.SearchCityBtn.Name = "SearchCityBtn";
            this.SearchCityBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.SearchCityBtn.OnDisabledState.BorderRadius = 1;
            this.SearchCityBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SearchCityBtn.OnDisabledState.BorderThickness = 1;
            this.SearchCityBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SearchCityBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.SearchCityBtn.OnDisabledState.IconLeftImage = null;
            this.SearchCityBtn.OnDisabledState.IconRightImage = null;
            this.SearchCityBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.SearchCityBtn.onHoverState.BorderRadius = 1;
            this.SearchCityBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SearchCityBtn.onHoverState.BorderThickness = 1;
            this.SearchCityBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.SearchCityBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.SearchCityBtn.onHoverState.IconLeftImage = null;
            this.SearchCityBtn.onHoverState.IconRightImage = null;
            this.SearchCityBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.SearchCityBtn.OnIdleState.BorderRadius = 1;
            this.SearchCityBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SearchCityBtn.OnIdleState.BorderThickness = 1;
            this.SearchCityBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.SearchCityBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.SearchCityBtn.OnIdleState.IconLeftImage = null;
            this.SearchCityBtn.OnIdleState.IconRightImage = null;
            this.SearchCityBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.SearchCityBtn.OnPressedState.BorderRadius = 1;
            this.SearchCityBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SearchCityBtn.OnPressedState.BorderThickness = 1;
            this.SearchCityBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.SearchCityBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.SearchCityBtn.OnPressedState.IconLeftImage = null;
            this.SearchCityBtn.OnPressedState.IconRightImage = null;
            this.SearchCityBtn.Size = new System.Drawing.Size(150, 39);
            this.SearchCityBtn.TabIndex = 12;
            this.SearchCityBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.SearchCityBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.SearchCityBtn.TextMarginLeft = 0;
            this.SearchCityBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.SearchCityBtn.UseDefaultRadiusAndThickness = true;
            // 
            // PrevBtn
            // 
            this.PrevBtn.AllowAnimations = true;
            this.PrevBtn.AllowMouseEffects = true;
            this.PrevBtn.AllowToggling = false;
            this.PrevBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.PrevBtn.AnimationSpeed = 200;
            this.PrevBtn.AutoGenerateColors = false;
            this.PrevBtn.AutoRoundBorders = false;
            this.PrevBtn.AutoSizeLeftIcon = true;
            this.PrevBtn.AutoSizeRightIcon = true;
            this.PrevBtn.BackColor = System.Drawing.Color.Transparent;
            this.PrevBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.PrevBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PrevBtn.BackgroundImage")));
            this.PrevBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PrevBtn.ButtonText = "Prev";
            this.PrevBtn.ButtonTextMarginLeft = 0;
            this.PrevBtn.ColorContrastOnClick = 45;
            this.PrevBtn.ColorContrastOnHover = 45;
            this.PrevBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.PrevBtn.CustomizableEdges = borderEdges5;
            this.PrevBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.PrevBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.PrevBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PrevBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.PrevBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.PrevBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.PrevBtn.ForeColor = System.Drawing.Color.White;
            this.PrevBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.PrevBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.PrevBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.PrevBtn.IconMarginLeft = 11;
            this.PrevBtn.IconPadding = 10;
            this.PrevBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.PrevBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.PrevBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.PrevBtn.IconSize = 25;
            this.PrevBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.PrevBtn.IdleBorderRadius = 1;
            this.PrevBtn.IdleBorderThickness = 1;
            this.PrevBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.PrevBtn.IdleIconLeftImage = null;
            this.PrevBtn.IdleIconRightImage = null;
            this.PrevBtn.IndicateFocus = false;
            this.PrevBtn.Location = new System.Drawing.Point(1046, 214);
            this.PrevBtn.Name = "PrevBtn";
            this.PrevBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.PrevBtn.OnDisabledState.BorderRadius = 1;
            this.PrevBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PrevBtn.OnDisabledState.BorderThickness = 1;
            this.PrevBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PrevBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.PrevBtn.OnDisabledState.IconLeftImage = null;
            this.PrevBtn.OnDisabledState.IconRightImage = null;
            this.PrevBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PrevBtn.onHoverState.BorderRadius = 1;
            this.PrevBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PrevBtn.onHoverState.BorderThickness = 1;
            this.PrevBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PrevBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.PrevBtn.onHoverState.IconLeftImage = null;
            this.PrevBtn.onHoverState.IconRightImage = null;
            this.PrevBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.PrevBtn.OnIdleState.BorderRadius = 1;
            this.PrevBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PrevBtn.OnIdleState.BorderThickness = 1;
            this.PrevBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.PrevBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.PrevBtn.OnIdleState.IconLeftImage = null;
            this.PrevBtn.OnIdleState.IconRightImage = null;
            this.PrevBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.PrevBtn.OnPressedState.BorderRadius = 1;
            this.PrevBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PrevBtn.OnPressedState.BorderThickness = 1;
            this.PrevBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.PrevBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.PrevBtn.OnPressedState.IconLeftImage = null;
            this.PrevBtn.OnPressedState.IconRightImage = null;
            this.PrevBtn.Size = new System.Drawing.Size(63, 39);
            this.PrevBtn.TabIndex = 13;
            this.PrevBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.PrevBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.PrevBtn.TextMarginLeft = 0;
            this.PrevBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.PrevBtn.UseDefaultRadiusAndThickness = true;
            this.PrevBtn.Click += new System.EventHandler(this.PrevBtn_Click);
            // 
            // NextBtn
            // 
            this.NextBtn.AllowAnimations = true;
            this.NextBtn.AllowMouseEffects = true;
            this.NextBtn.AllowToggling = false;
            this.NextBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.NextBtn.AnimationSpeed = 200;
            this.NextBtn.AutoGenerateColors = false;
            this.NextBtn.AutoRoundBorders = false;
            this.NextBtn.AutoSizeLeftIcon = true;
            this.NextBtn.AutoSizeRightIcon = true;
            this.NextBtn.BackColor = System.Drawing.Color.Transparent;
            this.NextBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.NextBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("NextBtn.BackgroundImage")));
            this.NextBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NextBtn.ButtonText = "Next";
            this.NextBtn.ButtonTextMarginLeft = 0;
            this.NextBtn.ColorContrastOnClick = 45;
            this.NextBtn.ColorContrastOnHover = 45;
            this.NextBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.NextBtn.CustomizableEdges = borderEdges6;
            this.NextBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.NextBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.NextBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.NextBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.NextBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.NextBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.NextBtn.ForeColor = System.Drawing.Color.White;
            this.NextBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.NextBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.NextBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.NextBtn.IconMarginLeft = 11;
            this.NextBtn.IconPadding = 10;
            this.NextBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.NextBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.NextBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.NextBtn.IconSize = 25;
            this.NextBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.NextBtn.IdleBorderRadius = 1;
            this.NextBtn.IdleBorderThickness = 1;
            this.NextBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.NextBtn.IdleIconLeftImage = null;
            this.NextBtn.IdleIconRightImage = null;
            this.NextBtn.IndicateFocus = false;
            this.NextBtn.Location = new System.Drawing.Point(1115, 214);
            this.NextBtn.Name = "NextBtn";
            this.NextBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.NextBtn.OnDisabledState.BorderRadius = 1;
            this.NextBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NextBtn.OnDisabledState.BorderThickness = 1;
            this.NextBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.NextBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.NextBtn.OnDisabledState.IconLeftImage = null;
            this.NextBtn.OnDisabledState.IconRightImage = null;
            this.NextBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.NextBtn.onHoverState.BorderRadius = 1;
            this.NextBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NextBtn.onHoverState.BorderThickness = 1;
            this.NextBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.NextBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.NextBtn.onHoverState.IconLeftImage = null;
            this.NextBtn.onHoverState.IconRightImage = null;
            this.NextBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.NextBtn.OnIdleState.BorderRadius = 1;
            this.NextBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NextBtn.OnIdleState.BorderThickness = 1;
            this.NextBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.NextBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.NextBtn.OnIdleState.IconLeftImage = null;
            this.NextBtn.OnIdleState.IconRightImage = null;
            this.NextBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.NextBtn.OnPressedState.BorderRadius = 1;
            this.NextBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NextBtn.OnPressedState.BorderThickness = 1;
            this.NextBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.NextBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.NextBtn.OnPressedState.IconLeftImage = null;
            this.NextBtn.OnPressedState.IconRightImage = null;
            this.NextBtn.Size = new System.Drawing.Size(58, 39);
            this.NextBtn.TabIndex = 14;
            this.NextBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.NextBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.NextBtn.TextMarginLeft = 0;
            this.NextBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.NextBtn.UseDefaultRadiusAndThickness = true;
            this.NextBtn.Click += new System.EventHandler(this.NextBtn_Click);
            // 
            // panel2
            // 
            this.panel2.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel2.Location = new System.Drawing.Point(0, 608);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(1200, 21);
            this.panel2.TabIndex = 15;
            // 
            // CityControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.NextBtn);
            this.Controls.Add(this.PrevBtn);
            this.Controls.Add(this.SearchCityBtn);
            this.Controls.Add(this.SearchCityTxt);
            this.Controls.Add(this.cityGrdiheadingLbl);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.CountryDatagridView);
            this.Name = "CityControl";
            this.Size = new System.Drawing.Size(1200, 629);
            ((System.ComponentModel.ISupportInitialize)(this.CountryDatagridView)).EndInit();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuTextBox CityNameTxt;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton SaveCityBtn;
        private Bunifu.UI.WinForms.BunifuDataGridView CountryDatagridView;
        private Bunifu.UI.WinForms.BunifuDropdown CountryDropDownLst;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label lblCityName;
        private Bunifu.UI.WinForms.BunifuTextBox cityIdTxt;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton UpdateCitybtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton PrintBtn;
        private System.Windows.Forms.PrintPreviewDialog CityPrintPreviewDialog;
        private System.Drawing.Printing.PrintDocument CityPrintDocument;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label cityGrdiheadingLbl;
        private Bunifu.UI.WinForms.BunifuTextBox SearchCityTxt;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton SearchCityBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton PrevBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton NextBtn;
        private System.Windows.Forms.Panel panel2;
    }
}
