// <auto-generated />
namespace POS_Shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class product_TblChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(product_TblChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "202509060819129_product_TblChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
