// <auto-generated />
namespace POS_Shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class edit_SalePriceCol_Type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit_SalePriceCol_Type));
        
        string IMigrationMetadata.Id
        {
            get { return "202510112055201_edit_SalePriceCol_Type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
