// <auto-generated />
namespace POS_Shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class TypeChane_Decimal_To_Int_PrductTbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TypeChane_Decimal_To_Int_PrductTbl));
        
        string IMigrationMetadata.Id
        {
            get { return "202509231004346_TypeChane_Decimal_To_Int_PrductTbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
