// <auto-generated />
namespace POS_Shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class add_qty_ProdTbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_qty_ProdTbl));
        
        string IMigrationMetadata.Id
        {
            get { return "202512161836217_add_qty_ProdTbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
