// <auto-generated />
namespace POS_Shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class removeEditQty_decimal_TempOdrDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeEditQty_decimal_TempOdrDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "202603022050233_removeEditQty_decimal_TempOdrDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
