// <auto-generated />
namespace POS_Shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class added_Prod_UniPrice_TotalActualBill_Profit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_Prod_UniPrice_TotalActualBill_Profit));
        
        string IMigrationMetadata.Id
        {
            get { return "202608061855482_added_Prod_UniPrice_TotalActualBill_Profit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
