namespace POS_Shop.Views.Controllers.RoleScreens
{
    partial class UserRoleControl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UserRoleControl));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.UserRoleFormLbl = new System.Windows.Forms.Label();
            this.panel1 = new System.Windows.Forms.Panel();
            this.ResetFromBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.RoleNameTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.UpdateRoleBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.lblCityName = new System.Windows.Forms.Label();
            this.SaveRoleBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.RoleIdTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.RoleDatagridView = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.NextBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.PrevBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.SearchRoleBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.SearchRoleTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.RoleDatagridView)).BeginInit();
            this.SuspendLayout();
            // 
            // UserRoleFormLbl
            // 
            this.UserRoleFormLbl.AutoSize = true;
            this.UserRoleFormLbl.Font = new System.Drawing.Font("Ravie", 12F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.UserRoleFormLbl.ForeColor = System.Drawing.Color.SlateBlue;
            this.UserRoleFormLbl.Location = new System.Drawing.Point(156, 23);
            this.UserRoleFormLbl.Name = "UserRoleFormLbl";
            this.UserRoleFormLbl.Size = new System.Drawing.Size(265, 27);
            this.UserRoleFormLbl.TabIndex = 17;
            this.UserRoleFormLbl.Text = "Role Form and List";
            // 
            // panel1
            // 
            this.panel1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panel1.AutoSize = true;
            this.panel1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panel1.Controls.Add(this.ResetFromBtn);
            this.panel1.Controls.Add(this.RoleNameTxt);
            this.panel1.Controls.Add(this.UpdateRoleBtn);
            this.panel1.Controls.Add(this.lblCityName);
            this.panel1.Controls.Add(this.SaveRoleBtn);
            this.panel1.Controls.Add(this.RoleIdTxt);
            this.panel1.Location = new System.Drawing.Point(19, 68);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1163, 94);
            this.panel1.TabIndex = 16;
            // 
            // ResetFromBtn
            // 
            this.ResetFromBtn.AllowAnimations = true;
            this.ResetFromBtn.AllowMouseEffects = true;
            this.ResetFromBtn.AllowToggling = false;
            this.ResetFromBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.ResetFromBtn.AnimationSpeed = 200;
            this.ResetFromBtn.AutoGenerateColors = false;
            this.ResetFromBtn.AutoRoundBorders = false;
            this.ResetFromBtn.AutoSizeLeftIcon = true;
            this.ResetFromBtn.AutoSizeRightIcon = true;
            this.ResetFromBtn.BackColor = System.Drawing.Color.Transparent;
            this.ResetFromBtn.BackColor1 = System.Drawing.Color.Red;
            this.ResetFromBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ResetFromBtn.BackgroundImage")));
            this.ResetFromBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ResetFromBtn.ButtonText = "Reset";
            this.ResetFromBtn.ButtonTextMarginLeft = 0;
            this.ResetFromBtn.ColorContrastOnClick = 45;
            this.ResetFromBtn.ColorContrastOnHover = 45;
            this.ResetFromBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.ResetFromBtn.CustomizableEdges = borderEdges1;
            this.ResetFromBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ResetFromBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ResetFromBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ResetFromBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ResetFromBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ResetFromBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ResetFromBtn.ForeColor = System.Drawing.Color.White;
            this.ResetFromBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ResetFromBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ResetFromBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ResetFromBtn.IconMarginLeft = 11;
            this.ResetFromBtn.IconPadding = 10;
            this.ResetFromBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ResetFromBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ResetFromBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ResetFromBtn.IconSize = 25;
            this.ResetFromBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.ResetFromBtn.IdleBorderRadius = 1;
            this.ResetFromBtn.IdleBorderThickness = 1;
            this.ResetFromBtn.IdleFillColor = System.Drawing.Color.Red;
            this.ResetFromBtn.IdleIconLeftImage = null;
            this.ResetFromBtn.IdleIconRightImage = null;
            this.ResetFromBtn.IndicateFocus = false;
            this.ResetFromBtn.Location = new System.Drawing.Point(846, 20);
            this.ResetFromBtn.Name = "ResetFromBtn";
            this.ResetFromBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ResetFromBtn.OnDisabledState.BorderRadius = 1;
            this.ResetFromBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ResetFromBtn.OnDisabledState.BorderThickness = 1;
            this.ResetFromBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ResetFromBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ResetFromBtn.OnDisabledState.IconLeftImage = null;
            this.ResetFromBtn.OnDisabledState.IconRightImage = null;
            this.ResetFromBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ResetFromBtn.onHoverState.BorderRadius = 1;
            this.ResetFromBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ResetFromBtn.onHoverState.BorderThickness = 1;
            this.ResetFromBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ResetFromBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ResetFromBtn.onHoverState.IconLeftImage = null;
            this.ResetFromBtn.onHoverState.IconRightImage = null;
            this.ResetFromBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.ResetFromBtn.OnIdleState.BorderRadius = 1;
            this.ResetFromBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ResetFromBtn.OnIdleState.BorderThickness = 1;
            this.ResetFromBtn.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.ResetFromBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.ResetFromBtn.OnIdleState.IconLeftImage = null;
            this.ResetFromBtn.OnIdleState.IconRightImage = null;
            this.ResetFromBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ResetFromBtn.OnPressedState.BorderRadius = 1;
            this.ResetFromBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ResetFromBtn.OnPressedState.BorderThickness = 1;
            this.ResetFromBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ResetFromBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ResetFromBtn.OnPressedState.IconLeftImage = null;
            this.ResetFromBtn.OnPressedState.IconRightImage = null;
            this.ResetFromBtn.Size = new System.Drawing.Size(150, 37);
            this.ResetFromBtn.TabIndex = 8;
            this.ResetFromBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ResetFromBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ResetFromBtn.TextMarginLeft = 0;
            this.ResetFromBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.ResetFromBtn.UseDefaultRadiusAndThickness = true;
            this.ResetFromBtn.Click += new System.EventHandler(this.ResetFromBtn_Click);
            // 
            // RoleNameTxt
            // 
            this.RoleNameTxt.AcceptsReturn = false;
            this.RoleNameTxt.AcceptsTab = false;
            this.RoleNameTxt.AnimationSpeed = 200;
            this.RoleNameTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.RoleNameTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.RoleNameTxt.BackColor = System.Drawing.Color.Transparent;
            this.RoleNameTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("RoleNameTxt.BackgroundImage")));
            this.RoleNameTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.RoleNameTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.RoleNameTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.RoleNameTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.RoleNameTxt.BorderRadius = 2;
            this.RoleNameTxt.BorderThickness = 1;
            this.RoleNameTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.RoleNameTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.RoleNameTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.RoleNameTxt.DefaultText = "";
            this.RoleNameTxt.FillColor = System.Drawing.Color.White;
            this.RoleNameTxt.HideSelection = true;
            this.RoleNameTxt.IconLeft = null;
            this.RoleNameTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.RoleNameTxt.IconPadding = 10;
            this.RoleNameTxt.IconRight = null;
            this.RoleNameTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.RoleNameTxt.Lines = new string[0];
            this.RoleNameTxt.Location = new System.Drawing.Point(108, 18);
            this.RoleNameTxt.MaxLength = 32767;
            this.RoleNameTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.RoleNameTxt.Modified = false;
            this.RoleNameTxt.Multiline = false;
            this.RoleNameTxt.Name = "RoleNameTxt";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.RoleNameTxt.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.RoleNameTxt.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.RoleNameTxt.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.RoleNameTxt.OnIdleState = stateProperties4;
            this.RoleNameTxt.Padding = new System.Windows.Forms.Padding(3);
            this.RoleNameTxt.PasswordChar = '\0';
            this.RoleNameTxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.RoleNameTxt.PlaceholderText = "Enter text";
            this.RoleNameTxt.ReadOnly = false;
            this.RoleNameTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.RoleNameTxt.SelectedText = "";
            this.RoleNameTxt.SelectionLength = 0;
            this.RoleNameTxt.SelectionStart = 0;
            this.RoleNameTxt.ShortcutsEnabled = true;
            this.RoleNameTxt.Size = new System.Drawing.Size(534, 41);
            this.RoleNameTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.RoleNameTxt.TabIndex = 1;
            this.RoleNameTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.RoleNameTxt.TextMarginBottom = 0;
            this.RoleNameTxt.TextMarginLeft = 3;
            this.RoleNameTxt.TextMarginTop = 0;
            this.RoleNameTxt.TextPlaceholder = "Enter text";
            this.RoleNameTxt.UseSystemPasswordChar = false;
            this.RoleNameTxt.WordWrap = true;
            // 
            // UpdateRoleBtn
            // 
            this.UpdateRoleBtn.AllowAnimations = true;
            this.UpdateRoleBtn.AllowMouseEffects = true;
            this.UpdateRoleBtn.AllowToggling = false;
            this.UpdateRoleBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.UpdateRoleBtn.AnimationSpeed = 200;
            this.UpdateRoleBtn.AutoGenerateColors = false;
            this.UpdateRoleBtn.AutoRoundBorders = false;
            this.UpdateRoleBtn.AutoSizeLeftIcon = true;
            this.UpdateRoleBtn.AutoSizeRightIcon = true;
            this.UpdateRoleBtn.BackColor = System.Drawing.Color.Transparent;
            this.UpdateRoleBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.UpdateRoleBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("UpdateRoleBtn.BackgroundImage")));
            this.UpdateRoleBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UpdateRoleBtn.ButtonText = "Update";
            this.UpdateRoleBtn.ButtonTextMarginLeft = 0;
            this.UpdateRoleBtn.ColorContrastOnClick = 45;
            this.UpdateRoleBtn.ColorContrastOnHover = 45;
            this.UpdateRoleBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.UpdateRoleBtn.CustomizableEdges = borderEdges2;
            this.UpdateRoleBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.UpdateRoleBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.UpdateRoleBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UpdateRoleBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.UpdateRoleBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.UpdateRoleBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.UpdateRoleBtn.ForeColor = System.Drawing.Color.White;
            this.UpdateRoleBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.UpdateRoleBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.UpdateRoleBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.UpdateRoleBtn.IconMarginLeft = 11;
            this.UpdateRoleBtn.IconPadding = 10;
            this.UpdateRoleBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.UpdateRoleBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.UpdateRoleBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.UpdateRoleBtn.IconSize = 25;
            this.UpdateRoleBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.UpdateRoleBtn.IdleBorderRadius = 1;
            this.UpdateRoleBtn.IdleBorderThickness = 1;
            this.UpdateRoleBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.UpdateRoleBtn.IdleIconLeftImage = null;
            this.UpdateRoleBtn.IdleIconRightImage = null;
            this.UpdateRoleBtn.IndicateFocus = false;
            this.UpdateRoleBtn.Location = new System.Drawing.Point(688, 20);
            this.UpdateRoleBtn.Name = "UpdateRoleBtn";
            this.UpdateRoleBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.UpdateRoleBtn.OnDisabledState.BorderRadius = 1;
            this.UpdateRoleBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UpdateRoleBtn.OnDisabledState.BorderThickness = 1;
            this.UpdateRoleBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UpdateRoleBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.UpdateRoleBtn.OnDisabledState.IconLeftImage = null;
            this.UpdateRoleBtn.OnDisabledState.IconRightImage = null;
            this.UpdateRoleBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.UpdateRoleBtn.onHoverState.BorderRadius = 1;
            this.UpdateRoleBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UpdateRoleBtn.onHoverState.BorderThickness = 1;
            this.UpdateRoleBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.UpdateRoleBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.UpdateRoleBtn.onHoverState.IconLeftImage = null;
            this.UpdateRoleBtn.onHoverState.IconRightImage = null;
            this.UpdateRoleBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.UpdateRoleBtn.OnIdleState.BorderRadius = 1;
            this.UpdateRoleBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UpdateRoleBtn.OnIdleState.BorderThickness = 1;
            this.UpdateRoleBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.UpdateRoleBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.UpdateRoleBtn.OnIdleState.IconLeftImage = null;
            this.UpdateRoleBtn.OnIdleState.IconRightImage = null;
            this.UpdateRoleBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.UpdateRoleBtn.OnPressedState.BorderRadius = 1;
            this.UpdateRoleBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UpdateRoleBtn.OnPressedState.BorderThickness = 1;
            this.UpdateRoleBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.UpdateRoleBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.UpdateRoleBtn.OnPressedState.IconLeftImage = null;
            this.UpdateRoleBtn.OnPressedState.IconRightImage = null;
            this.UpdateRoleBtn.Size = new System.Drawing.Size(150, 37);
            this.UpdateRoleBtn.TabIndex = 4;
            this.UpdateRoleBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.UpdateRoleBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.UpdateRoleBtn.TextMarginLeft = 0;
            this.UpdateRoleBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.UpdateRoleBtn.UseDefaultRadiusAndThickness = true;
            this.UpdateRoleBtn.Visible = false;
            this.UpdateRoleBtn.Click += new System.EventHandler(this.UpdateRoleBtn_Click);
            // 
            // lblCityName
            // 
            this.lblCityName.AutoSize = true;
            this.lblCityName.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCityName.Location = new System.Drawing.Point(10, 23);
            this.lblCityName.Name = "lblCityName";
            this.lblCityName.Size = new System.Drawing.Size(92, 18);
            this.lblCityName.TabIndex = 0;
            this.lblCityName.Text = "Role Name";
            // 
            // SaveRoleBtn
            // 
            this.SaveRoleBtn.AllowAnimations = true;
            this.SaveRoleBtn.AllowMouseEffects = true;
            this.SaveRoleBtn.AllowToggling = false;
            this.SaveRoleBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.SaveRoleBtn.AnimationSpeed = 200;
            this.SaveRoleBtn.AutoGenerateColors = false;
            this.SaveRoleBtn.AutoRoundBorders = false;
            this.SaveRoleBtn.AutoSizeLeftIcon = true;
            this.SaveRoleBtn.AutoSizeRightIcon = true;
            this.SaveRoleBtn.BackColor = System.Drawing.Color.Transparent;
            this.SaveRoleBtn.BackColor1 = System.Drawing.Color.SlateBlue;
            this.SaveRoleBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("SaveRoleBtn.BackgroundImage")));
            this.SaveRoleBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SaveRoleBtn.ButtonText = "Save";
            this.SaveRoleBtn.ButtonTextMarginLeft = 0;
            this.SaveRoleBtn.ColorContrastOnClick = 45;
            this.SaveRoleBtn.ColorContrastOnHover = 45;
            this.SaveRoleBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.SaveRoleBtn.CustomizableEdges = borderEdges3;
            this.SaveRoleBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.SaveRoleBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.SaveRoleBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SaveRoleBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.SaveRoleBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.SaveRoleBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.SaveRoleBtn.ForeColor = System.Drawing.Color.White;
            this.SaveRoleBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.SaveRoleBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.SaveRoleBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.SaveRoleBtn.IconMarginLeft = 11;
            this.SaveRoleBtn.IconPadding = 10;
            this.SaveRoleBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.SaveRoleBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.SaveRoleBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.SaveRoleBtn.IconSize = 25;
            this.SaveRoleBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.SaveRoleBtn.IdleBorderRadius = 1;
            this.SaveRoleBtn.IdleBorderThickness = 1;
            this.SaveRoleBtn.IdleFillColor = System.Drawing.Color.SlateBlue;
            this.SaveRoleBtn.IdleIconLeftImage = null;
            this.SaveRoleBtn.IdleIconRightImage = null;
            this.SaveRoleBtn.IndicateFocus = false;
            this.SaveRoleBtn.Location = new System.Drawing.Point(1004, 20);
            this.SaveRoleBtn.Name = "SaveRoleBtn";
            this.SaveRoleBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.SaveRoleBtn.OnDisabledState.BorderRadius = 1;
            this.SaveRoleBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SaveRoleBtn.OnDisabledState.BorderThickness = 1;
            this.SaveRoleBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SaveRoleBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.SaveRoleBtn.OnDisabledState.IconLeftImage = null;
            this.SaveRoleBtn.OnDisabledState.IconRightImage = null;
            this.SaveRoleBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.SaveRoleBtn.onHoverState.BorderRadius = 1;
            this.SaveRoleBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SaveRoleBtn.onHoverState.BorderThickness = 1;
            this.SaveRoleBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.SaveRoleBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.SaveRoleBtn.onHoverState.IconLeftImage = null;
            this.SaveRoleBtn.onHoverState.IconRightImage = null;
            this.SaveRoleBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.SaveRoleBtn.OnIdleState.BorderRadius = 1;
            this.SaveRoleBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SaveRoleBtn.OnIdleState.BorderThickness = 1;
            this.SaveRoleBtn.OnIdleState.FillColor = System.Drawing.Color.SlateBlue;
            this.SaveRoleBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.SaveRoleBtn.OnIdleState.IconLeftImage = null;
            this.SaveRoleBtn.OnIdleState.IconRightImage = null;
            this.SaveRoleBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.SaveRoleBtn.OnPressedState.BorderRadius = 1;
            this.SaveRoleBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SaveRoleBtn.OnPressedState.BorderThickness = 1;
            this.SaveRoleBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.SaveRoleBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.SaveRoleBtn.OnPressedState.IconLeftImage = null;
            this.SaveRoleBtn.OnPressedState.IconRightImage = null;
            this.SaveRoleBtn.Size = new System.Drawing.Size(150, 39);
            this.SaveRoleBtn.TabIndex = 3;
            this.SaveRoleBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.SaveRoleBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.SaveRoleBtn.TextMarginLeft = 0;
            this.SaveRoleBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.SaveRoleBtn.UseDefaultRadiusAndThickness = true;
            this.SaveRoleBtn.Click += new System.EventHandler(this.SaveRoleBtn_Click);
            // 
            // RoleIdTxt
            // 
            this.RoleIdTxt.AcceptsReturn = false;
            this.RoleIdTxt.AcceptsTab = false;
            this.RoleIdTxt.AnimationSpeed = 200;
            this.RoleIdTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.RoleIdTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.RoleIdTxt.BackColor = System.Drawing.Color.Transparent;
            this.RoleIdTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("RoleIdTxt.BackgroundImage")));
            this.RoleIdTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.RoleIdTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.RoleIdTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.RoleIdTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.RoleIdTxt.BorderRadius = 1;
            this.RoleIdTxt.BorderThickness = 1;
            this.RoleIdTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.RoleIdTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.RoleIdTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.RoleIdTxt.DefaultText = "";
            this.RoleIdTxt.FillColor = System.Drawing.Color.White;
            this.RoleIdTxt.HideSelection = true;
            this.RoleIdTxt.IconLeft = null;
            this.RoleIdTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.RoleIdTxt.IconPadding = 10;
            this.RoleIdTxt.IconRight = null;
            this.RoleIdTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.RoleIdTxt.Lines = new string[0];
            this.RoleIdTxt.Location = new System.Drawing.Point(3, 44);
            this.RoleIdTxt.MaxLength = 32767;
            this.RoleIdTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.RoleIdTxt.Modified = false;
            this.RoleIdTxt.Multiline = false;
            this.RoleIdTxt.Name = "RoleIdTxt";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.RoleIdTxt.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.RoleIdTxt.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.RoleIdTxt.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.RoleIdTxt.OnIdleState = stateProperties8;
            this.RoleIdTxt.Padding = new System.Windows.Forms.Padding(3);
            this.RoleIdTxt.PasswordChar = '\0';
            this.RoleIdTxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.RoleIdTxt.PlaceholderText = "Enter text";
            this.RoleIdTxt.ReadOnly = false;
            this.RoleIdTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.RoleIdTxt.SelectedText = "";
            this.RoleIdTxt.SelectionLength = 0;
            this.RoleIdTxt.SelectionStart = 0;
            this.RoleIdTxt.ShortcutsEnabled = true;
            this.RoleIdTxt.Size = new System.Drawing.Size(101, 25);
            this.RoleIdTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.RoleIdTxt.TabIndex = 6;
            this.RoleIdTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.RoleIdTxt.TextMarginBottom = 0;
            this.RoleIdTxt.TextMarginLeft = 3;
            this.RoleIdTxt.TextMarginTop = 0;
            this.RoleIdTxt.TextPlaceholder = "Enter text";
            this.RoleIdTxt.UseSystemPasswordChar = false;
            this.RoleIdTxt.Visible = false;
            this.RoleIdTxt.WordWrap = true;
            // 
            // RoleDatagridView
            // 
            this.RoleDatagridView.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.RoleDatagridView.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.RoleDatagridView.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.RoleDatagridView.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.RoleDatagridView.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.RoleDatagridView.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.RoleDatagridView.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.RoleDatagridView.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.RoleDatagridView.ColumnHeadersHeight = 40;
            this.RoleDatagridView.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.RoleDatagridView.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.RoleDatagridView.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.RoleDatagridView.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.RoleDatagridView.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.RoleDatagridView.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.RoleDatagridView.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.RoleDatagridView.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.RoleDatagridView.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.RoleDatagridView.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.RoleDatagridView.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.RoleDatagridView.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.RoleDatagridView.CurrentTheme.Name = null;
            this.RoleDatagridView.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.RoleDatagridView.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.RoleDatagridView.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.RoleDatagridView.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.RoleDatagridView.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.RoleDatagridView.DefaultCellStyle = dataGridViewCellStyle3;
            this.RoleDatagridView.EnableHeadersVisualStyles = false;
            this.RoleDatagridView.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.RoleDatagridView.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.RoleDatagridView.HeaderBgColor = System.Drawing.Color.Empty;
            this.RoleDatagridView.HeaderForeColor = System.Drawing.Color.White;
            this.RoleDatagridView.Location = new System.Drawing.Point(19, 242);
            this.RoleDatagridView.Name = "RoleDatagridView";
            this.RoleDatagridView.RowHeadersVisible = false;
            this.RoleDatagridView.RowHeadersWidth = 51;
            this.RoleDatagridView.RowTemplate.Height = 40;
            this.RoleDatagridView.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.RoleDatagridView.Size = new System.Drawing.Size(1156, 364);
            this.RoleDatagridView.TabIndex = 15;
            this.RoleDatagridView.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.RoleDatagridView.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.RoleDatagridView_CellClick);
            // 
            // NextBtn
            // 
            this.NextBtn.AllowAnimations = true;
            this.NextBtn.AllowMouseEffects = true;
            this.NextBtn.AllowToggling = false;
            this.NextBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.NextBtn.AnimationSpeed = 200;
            this.NextBtn.AutoGenerateColors = false;
            this.NextBtn.AutoRoundBorders = false;
            this.NextBtn.AutoSizeLeftIcon = true;
            this.NextBtn.AutoSizeRightIcon = true;
            this.NextBtn.BackColor = System.Drawing.Color.Transparent;
            this.NextBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.NextBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("NextBtn.BackgroundImage")));
            this.NextBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NextBtn.ButtonText = "Next";
            this.NextBtn.ButtonTextMarginLeft = 0;
            this.NextBtn.ColorContrastOnClick = 45;
            this.NextBtn.ColorContrastOnHover = 45;
            this.NextBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.NextBtn.CustomizableEdges = borderEdges4;
            this.NextBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.NextBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.NextBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.NextBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.NextBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.NextBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.NextBtn.ForeColor = System.Drawing.Color.White;
            this.NextBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.NextBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.NextBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.NextBtn.IconMarginLeft = 11;
            this.NextBtn.IconPadding = 10;
            this.NextBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.NextBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.NextBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.NextBtn.IconSize = 25;
            this.NextBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.NextBtn.IdleBorderRadius = 1;
            this.NextBtn.IdleBorderThickness = 1;
            this.NextBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.NextBtn.IdleIconLeftImage = null;
            this.NextBtn.IdleIconRightImage = null;
            this.NextBtn.IndicateFocus = false;
            this.NextBtn.Location = new System.Drawing.Point(1117, 178);
            this.NextBtn.Name = "NextBtn";
            this.NextBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.NextBtn.OnDisabledState.BorderRadius = 1;
            this.NextBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NextBtn.OnDisabledState.BorderThickness = 1;
            this.NextBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.NextBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.NextBtn.OnDisabledState.IconLeftImage = null;
            this.NextBtn.OnDisabledState.IconRightImage = null;
            this.NextBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.NextBtn.onHoverState.BorderRadius = 1;
            this.NextBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NextBtn.onHoverState.BorderThickness = 1;
            this.NextBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.NextBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.NextBtn.onHoverState.IconLeftImage = null;
            this.NextBtn.onHoverState.IconRightImage = null;
            this.NextBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.NextBtn.OnIdleState.BorderRadius = 1;
            this.NextBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NextBtn.OnIdleState.BorderThickness = 1;
            this.NextBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.NextBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.NextBtn.OnIdleState.IconLeftImage = null;
            this.NextBtn.OnIdleState.IconRightImage = null;
            this.NextBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.NextBtn.OnPressedState.BorderRadius = 1;
            this.NextBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NextBtn.OnPressedState.BorderThickness = 1;
            this.NextBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.NextBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.NextBtn.OnPressedState.IconLeftImage = null;
            this.NextBtn.OnPressedState.IconRightImage = null;
            this.NextBtn.Size = new System.Drawing.Size(58, 39);
            this.NextBtn.TabIndex = 21;
            this.NextBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.NextBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.NextBtn.TextMarginLeft = 0;
            this.NextBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.NextBtn.UseDefaultRadiusAndThickness = true;
            this.NextBtn.Click += new System.EventHandler(this.NextBtn_Click);
            // 
            // PrevBtn
            // 
            this.PrevBtn.AllowAnimations = true;
            this.PrevBtn.AllowMouseEffects = true;
            this.PrevBtn.AllowToggling = false;
            this.PrevBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.PrevBtn.AnimationSpeed = 200;
            this.PrevBtn.AutoGenerateColors = false;
            this.PrevBtn.AutoRoundBorders = false;
            this.PrevBtn.AutoSizeLeftIcon = true;
            this.PrevBtn.AutoSizeRightIcon = true;
            this.PrevBtn.BackColor = System.Drawing.Color.Transparent;
            this.PrevBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.PrevBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PrevBtn.BackgroundImage")));
            this.PrevBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PrevBtn.ButtonText = "Prev";
            this.PrevBtn.ButtonTextMarginLeft = 0;
            this.PrevBtn.ColorContrastOnClick = 45;
            this.PrevBtn.ColorContrastOnHover = 45;
            this.PrevBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.PrevBtn.CustomizableEdges = borderEdges5;
            this.PrevBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.PrevBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.PrevBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PrevBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.PrevBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.PrevBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.PrevBtn.ForeColor = System.Drawing.Color.White;
            this.PrevBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.PrevBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.PrevBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.PrevBtn.IconMarginLeft = 11;
            this.PrevBtn.IconPadding = 10;
            this.PrevBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.PrevBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.PrevBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.PrevBtn.IconSize = 25;
            this.PrevBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.PrevBtn.IdleBorderRadius = 1;
            this.PrevBtn.IdleBorderThickness = 1;
            this.PrevBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.PrevBtn.IdleIconLeftImage = null;
            this.PrevBtn.IdleIconRightImage = null;
            this.PrevBtn.IndicateFocus = false;
            this.PrevBtn.Location = new System.Drawing.Point(1048, 178);
            this.PrevBtn.Name = "PrevBtn";
            this.PrevBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.PrevBtn.OnDisabledState.BorderRadius = 1;
            this.PrevBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PrevBtn.OnDisabledState.BorderThickness = 1;
            this.PrevBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PrevBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.PrevBtn.OnDisabledState.IconLeftImage = null;
            this.PrevBtn.OnDisabledState.IconRightImage = null;
            this.PrevBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PrevBtn.onHoverState.BorderRadius = 1;
            this.PrevBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PrevBtn.onHoverState.BorderThickness = 1;
            this.PrevBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PrevBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.PrevBtn.onHoverState.IconLeftImage = null;
            this.PrevBtn.onHoverState.IconRightImage = null;
            this.PrevBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.PrevBtn.OnIdleState.BorderRadius = 1;
            this.PrevBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PrevBtn.OnIdleState.BorderThickness = 1;
            this.PrevBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.PrevBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.PrevBtn.OnIdleState.IconLeftImage = null;
            this.PrevBtn.OnIdleState.IconRightImage = null;
            this.PrevBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.PrevBtn.OnPressedState.BorderRadius = 1;
            this.PrevBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PrevBtn.OnPressedState.BorderThickness = 1;
            this.PrevBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.PrevBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.PrevBtn.OnPressedState.IconLeftImage = null;
            this.PrevBtn.OnPressedState.IconRightImage = null;
            this.PrevBtn.Size = new System.Drawing.Size(63, 39);
            this.PrevBtn.TabIndex = 20;
            this.PrevBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.PrevBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.PrevBtn.TextMarginLeft = 0;
            this.PrevBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.PrevBtn.UseDefaultRadiusAndThickness = true;
            this.PrevBtn.Click += new System.EventHandler(this.PrevBtn_Click);
            // 
            // SearchRoleBtn
            // 
            this.SearchRoleBtn.AllowAnimations = true;
            this.SearchRoleBtn.AllowMouseEffects = true;
            this.SearchRoleBtn.AllowToggling = false;
            this.SearchRoleBtn.AnimationSpeed = 200;
            this.SearchRoleBtn.AutoGenerateColors = false;
            this.SearchRoleBtn.AutoRoundBorders = false;
            this.SearchRoleBtn.AutoSizeLeftIcon = true;
            this.SearchRoleBtn.AutoSizeRightIcon = true;
            this.SearchRoleBtn.BackColor = System.Drawing.Color.Transparent;
            this.SearchRoleBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.SearchRoleBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("SearchRoleBtn.BackgroundImage")));
            this.SearchRoleBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SearchRoleBtn.ButtonText = "Search";
            this.SearchRoleBtn.ButtonTextMarginLeft = 0;
            this.SearchRoleBtn.ColorContrastOnClick = 45;
            this.SearchRoleBtn.ColorContrastOnHover = 45;
            this.SearchRoleBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.SearchRoleBtn.CustomizableEdges = borderEdges6;
            this.SearchRoleBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.SearchRoleBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.SearchRoleBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SearchRoleBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.SearchRoleBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.SearchRoleBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.SearchRoleBtn.ForeColor = System.Drawing.Color.White;
            this.SearchRoleBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.SearchRoleBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.SearchRoleBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.SearchRoleBtn.IconMarginLeft = 11;
            this.SearchRoleBtn.IconPadding = 10;
            this.SearchRoleBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.SearchRoleBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.SearchRoleBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.SearchRoleBtn.IconSize = 25;
            this.SearchRoleBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.SearchRoleBtn.IdleBorderRadius = 1;
            this.SearchRoleBtn.IdleBorderThickness = 1;
            this.SearchRoleBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.SearchRoleBtn.IdleIconLeftImage = null;
            this.SearchRoleBtn.IdleIconRightImage = null;
            this.SearchRoleBtn.IndicateFocus = false;
            this.SearchRoleBtn.Location = new System.Drawing.Point(579, 177);
            this.SearchRoleBtn.Name = "SearchRoleBtn";
            this.SearchRoleBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.SearchRoleBtn.OnDisabledState.BorderRadius = 1;
            this.SearchRoleBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SearchRoleBtn.OnDisabledState.BorderThickness = 1;
            this.SearchRoleBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SearchRoleBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.SearchRoleBtn.OnDisabledState.IconLeftImage = null;
            this.SearchRoleBtn.OnDisabledState.IconRightImage = null;
            this.SearchRoleBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.SearchRoleBtn.onHoverState.BorderRadius = 1;
            this.SearchRoleBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SearchRoleBtn.onHoverState.BorderThickness = 1;
            this.SearchRoleBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.SearchRoleBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.SearchRoleBtn.onHoverState.IconLeftImage = null;
            this.SearchRoleBtn.onHoverState.IconRightImage = null;
            this.SearchRoleBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.SearchRoleBtn.OnIdleState.BorderRadius = 1;
            this.SearchRoleBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SearchRoleBtn.OnIdleState.BorderThickness = 1;
            this.SearchRoleBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.SearchRoleBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.SearchRoleBtn.OnIdleState.IconLeftImage = null;
            this.SearchRoleBtn.OnIdleState.IconRightImage = null;
            this.SearchRoleBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.SearchRoleBtn.OnPressedState.BorderRadius = 1;
            this.SearchRoleBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SearchRoleBtn.OnPressedState.BorderThickness = 1;
            this.SearchRoleBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.SearchRoleBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.SearchRoleBtn.OnPressedState.IconLeftImage = null;
            this.SearchRoleBtn.OnPressedState.IconRightImage = null;
            this.SearchRoleBtn.Size = new System.Drawing.Size(150, 39);
            this.SearchRoleBtn.TabIndex = 19;
            this.SearchRoleBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.SearchRoleBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.SearchRoleBtn.TextMarginLeft = 0;
            this.SearchRoleBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.SearchRoleBtn.UseDefaultRadiusAndThickness = true;
            // 
            // SearchRoleTxt
            // 
            this.SearchRoleTxt.AcceptsReturn = false;
            this.SearchRoleTxt.AcceptsTab = false;
            this.SearchRoleTxt.AnimationSpeed = 200;
            this.SearchRoleTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.SearchRoleTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.SearchRoleTxt.BackColor = System.Drawing.Color.Transparent;
            this.SearchRoleTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("SearchRoleTxt.BackgroundImage")));
            this.SearchRoleTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.SearchRoleTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SearchRoleTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.SearchRoleTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.SearchRoleTxt.BorderRadius = 1;
            this.SearchRoleTxt.BorderThickness = 1;
            this.SearchRoleTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.SearchRoleTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.SearchRoleTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.SearchRoleTxt.DefaultText = "";
            this.SearchRoleTxt.FillColor = System.Drawing.Color.White;
            this.SearchRoleTxt.HideSelection = true;
            this.SearchRoleTxt.IconLeft = null;
            this.SearchRoleTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.SearchRoleTxt.IconPadding = 10;
            this.SearchRoleTxt.IconRight = null;
            this.SearchRoleTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.SearchRoleTxt.Lines = new string[0];
            this.SearchRoleTxt.Location = new System.Drawing.Point(19, 177);
            this.SearchRoleTxt.MaxLength = 32767;
            this.SearchRoleTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.SearchRoleTxt.Modified = false;
            this.SearchRoleTxt.Multiline = false;
            this.SearchRoleTxt.Name = "SearchRoleTxt";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.SearchRoleTxt.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.SearchRoleTxt.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.SearchRoleTxt.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.SearchRoleTxt.OnIdleState = stateProperties12;
            this.SearchRoleTxt.Padding = new System.Windows.Forms.Padding(3);
            this.SearchRoleTxt.PasswordChar = '\0';
            this.SearchRoleTxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.SearchRoleTxt.PlaceholderText = "Search Role";
            this.SearchRoleTxt.ReadOnly = false;
            this.SearchRoleTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.SearchRoleTxt.SelectedText = "";
            this.SearchRoleTxt.SelectionLength = 0;
            this.SearchRoleTxt.SelectionStart = 0;
            this.SearchRoleTxt.ShortcutsEnabled = true;
            this.SearchRoleTxt.Size = new System.Drawing.Size(554, 41);
            this.SearchRoleTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.SearchRoleTxt.TabIndex = 18;
            this.SearchRoleTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.SearchRoleTxt.TextMarginBottom = 0;
            this.SearchRoleTxt.TextMarginLeft = 3;
            this.SearchRoleTxt.TextMarginTop = 0;
            this.SearchRoleTxt.TextPlaceholder = "Search Role";
            this.SearchRoleTxt.UseSystemPasswordChar = false;
            this.SearchRoleTxt.WordWrap = true;
            this.SearchRoleTxt.TextChange += new System.EventHandler(this.SearchRoleTxt_TextChange);
            // 
            // UserRoleControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.UserRoleFormLbl);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.NextBtn);
            this.Controls.Add(this.PrevBtn);
            this.Controls.Add(this.SearchRoleBtn);
            this.Controls.Add(this.SearchRoleTxt);
            this.Controls.Add(this.RoleDatagridView);
            this.Name = "UserRoleControl";
            this.Size = new System.Drawing.Size(1200, 629);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.RoleDatagridView)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label UserRoleFormLbl;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ResetFromBtn;
        private Bunifu.UI.WinForms.BunifuTextBox RoleNameTxt;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton UpdateRoleBtn;
        private System.Windows.Forms.Label lblCityName;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton SaveRoleBtn;
        private Bunifu.UI.WinForms.BunifuTextBox RoleIdTxt;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton NextBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton PrevBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton SearchRoleBtn;
        private Bunifu.UI.WinForms.BunifuTextBox SearchRoleTxt;
        private Bunifu.UI.WinForms.BunifuDataGridView RoleDatagridView;
    }
}
