namespace POS_Shop.Views.Product
{
    partial class ProductFromControl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ProductFromControl));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties85 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties86 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties87 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties88 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges13 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges14 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties89 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties90 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties91 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties92 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties93 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties94 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties95 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties96 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties97 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties98 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties99 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties100 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties101 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties102 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties103 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties104 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties105 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties106 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties107 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties108 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties109 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties110 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties111 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties112 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges15 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges16 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.ProductFromGrp = new System.Windows.Forms.GroupBox();
            this.P_typeLbl = new System.Windows.Forms.Label();
            this.productTypeDropdown = new Bunifu.UI.WinForms.BunifuDropdown();
            this.P_costLbl = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.SubCategoryCategoryDropDownLst = new Bunifu.UI.WinForms.BunifuDropdown();
            this.CategoryDropDownLst = new Bunifu.UI.WinForms.BunifuDropdown();
            this.CategoryDropdownLbl = new System.Windows.Forms.Label();
            this.StockQtyLbl = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.P_SaleLbl = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.backgroundWorker1 = new System.ComponentModel.BackgroundWorker();
            this.backgroundWorker2 = new System.ComponentModel.BackgroundWorker();
            this.ProductListGridGrp = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.ProductListGrid = new System.Windows.Forms.DataGridView();
            this.p_costTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ProductSaveBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.P_StockQtyTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.PurchasePriceTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.P_SalePriceTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ProductUrduNameTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ProductEngNameTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ProdSearchTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.NextBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.PrevBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.lblStatus = new System.Windows.Forms.Label();
            this.ProductFromGrp.SuspendLayout();
            this.ProductListGridGrp.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ProductListGrid)).BeginInit();
            this.SuspendLayout();
            // 
            // ProductFromGrp
            // 
            this.ProductFromGrp.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.ProductFromGrp.Controls.Add(this.P_typeLbl);
            this.ProductFromGrp.Controls.Add(this.productTypeDropdown);
            this.ProductFromGrp.Controls.Add(this.P_costLbl);
            this.ProductFromGrp.Controls.Add(this.p_costTxt);
            this.ProductFromGrp.Controls.Add(this.bunifuButton2);
            this.ProductFromGrp.Controls.Add(this.ProductSaveBtn);
            this.ProductFromGrp.Controls.Add(this.label4);
            this.ProductFromGrp.Controls.Add(this.SubCategoryCategoryDropDownLst);
            this.ProductFromGrp.Controls.Add(this.CategoryDropDownLst);
            this.ProductFromGrp.Controls.Add(this.CategoryDropdownLbl);
            this.ProductFromGrp.Controls.Add(this.P_StockQtyTxt);
            this.ProductFromGrp.Controls.Add(this.StockQtyLbl);
            this.ProductFromGrp.Controls.Add(this.PurchasePriceTxt);
            this.ProductFromGrp.Controls.Add(this.label3);
            this.ProductFromGrp.Controls.Add(this.P_SaleLbl);
            this.ProductFromGrp.Controls.Add(this.P_SalePriceTxt);
            this.ProductFromGrp.Controls.Add(this.ProductUrduNameTxt);
            this.ProductFromGrp.Controls.Add(this.ProductEngNameTxt);
            this.ProductFromGrp.Controls.Add(this.label2);
            this.ProductFromGrp.Controls.Add(this.label1);
            this.ProductFromGrp.Location = new System.Drawing.Point(15, 36);
            this.ProductFromGrp.Name = "ProductFromGrp";
            this.ProductFromGrp.Size = new System.Drawing.Size(1292, 182);
            this.ProductFromGrp.TabIndex = 0;
            this.ProductFromGrp.TabStop = false;
            this.ProductFromGrp.Text = "Product Form";
            // 
            // P_typeLbl
            // 
            this.P_typeLbl.AutoSize = true;
            this.P_typeLbl.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.P_typeLbl.Location = new System.Drawing.Point(725, 34);
            this.P_typeLbl.Name = "P_typeLbl";
            this.P_typeLbl.Size = new System.Drawing.Size(43, 16);
            this.P_typeLbl.TabIndex = 0;
            this.P_typeLbl.Text = "Type";
            // 
            // productTypeDropdown
            // 
            this.productTypeDropdown.BackColor = System.Drawing.Color.Transparent;
            this.productTypeDropdown.BackgroundColor = System.Drawing.Color.White;
            this.productTypeDropdown.BorderColor = System.Drawing.Color.Silver;
            this.productTypeDropdown.BorderRadius = 1;
            this.productTypeDropdown.Color = System.Drawing.Color.Silver;
            this.productTypeDropdown.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.productTypeDropdown.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.productTypeDropdown.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.productTypeDropdown.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.productTypeDropdown.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.productTypeDropdown.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.productTypeDropdown.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.productTypeDropdown.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.productTypeDropdown.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.productTypeDropdown.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.productTypeDropdown.FillDropDown = true;
            this.productTypeDropdown.FillIndicator = false;
            this.productTypeDropdown.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.productTypeDropdown.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.productTypeDropdown.ForeColor = System.Drawing.Color.Black;
            this.productTypeDropdown.FormattingEnabled = true;
            this.productTypeDropdown.Icon = null;
            this.productTypeDropdown.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.productTypeDropdown.IndicatorColor = System.Drawing.Color.Gray;
            this.productTypeDropdown.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.productTypeDropdown.ItemBackColor = System.Drawing.Color.White;
            this.productTypeDropdown.ItemBorderColor = System.Drawing.Color.White;
            this.productTypeDropdown.ItemForeColor = System.Drawing.Color.Black;
            this.productTypeDropdown.ItemHeight = 26;
            this.productTypeDropdown.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.productTypeDropdown.ItemHighLightForeColor = System.Drawing.Color.White;
            this.productTypeDropdown.Items.AddRange(new object[] {
            "عدد",
            "ڈبہ",
            "درجن",
            "کارٹن",
            "پیکٹ",
            "رول",
            "گز"});
            this.productTypeDropdown.ItemTopMargin = 3;
            this.productTypeDropdown.Location = new System.Drawing.Point(777, 26);
            this.productTypeDropdown.Name = "productTypeDropdown";
            this.productTypeDropdown.Size = new System.Drawing.Size(96, 32);
            this.productTypeDropdown.TabIndex = 3;
            this.productTypeDropdown.Text = null;
            this.productTypeDropdown.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.productTypeDropdown.TextLeftMargin = 5;
            // 
            // P_costLbl
            // 
            this.P_costLbl.AutoSize = true;
            this.P_costLbl.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.P_costLbl.Location = new System.Drawing.Point(10, 89);
            this.P_costLbl.Name = "P_costLbl";
            this.P_costLbl.Size = new System.Drawing.Size(38, 16);
            this.P_costLbl.TabIndex = 0;
            this.P_costLbl.Text = "Cost";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(821, 87);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(102, 16);
            this.label4.TabIndex = 0;
            this.label4.Text = "Sub-Category";
            // 
            // SubCategoryCategoryDropDownLst
            // 
            this.SubCategoryCategoryDropDownLst.BackColor = System.Drawing.Color.Transparent;
            this.SubCategoryCategoryDropDownLst.BackgroundColor = System.Drawing.Color.White;
            this.SubCategoryCategoryDropDownLst.BorderColor = System.Drawing.Color.Silver;
            this.SubCategoryCategoryDropDownLst.BorderRadius = 1;
            this.SubCategoryCategoryDropDownLst.Color = System.Drawing.Color.Silver;
            this.SubCategoryCategoryDropDownLst.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.SubCategoryCategoryDropDownLst.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.SubCategoryCategoryDropDownLst.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SubCategoryCategoryDropDownLst.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.SubCategoryCategoryDropDownLst.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.SubCategoryCategoryDropDownLst.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.SubCategoryCategoryDropDownLst.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.SubCategoryCategoryDropDownLst.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.SubCategoryCategoryDropDownLst.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.SubCategoryCategoryDropDownLst.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.SubCategoryCategoryDropDownLst.FillDropDown = true;
            this.SubCategoryCategoryDropDownLst.FillIndicator = false;
            this.SubCategoryCategoryDropDownLst.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.SubCategoryCategoryDropDownLst.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.SubCategoryCategoryDropDownLst.ForeColor = System.Drawing.Color.Black;
            this.SubCategoryCategoryDropDownLst.FormattingEnabled = true;
            this.SubCategoryCategoryDropDownLst.Icon = null;
            this.SubCategoryCategoryDropDownLst.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.SubCategoryCategoryDropDownLst.IndicatorColor = System.Drawing.Color.Gray;
            this.SubCategoryCategoryDropDownLst.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.SubCategoryCategoryDropDownLst.ItemBackColor = System.Drawing.Color.White;
            this.SubCategoryCategoryDropDownLst.ItemBorderColor = System.Drawing.Color.White;
            this.SubCategoryCategoryDropDownLst.ItemForeColor = System.Drawing.Color.Black;
            this.SubCategoryCategoryDropDownLst.ItemHeight = 26;
            this.SubCategoryCategoryDropDownLst.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.SubCategoryCategoryDropDownLst.ItemHighLightForeColor = System.Drawing.Color.White;
            this.SubCategoryCategoryDropDownLst.ItemTopMargin = 3;
            this.SubCategoryCategoryDropDownLst.Location = new System.Drawing.Point(935, 78);
            this.SubCategoryCategoryDropDownLst.Name = "SubCategoryCategoryDropDownLst";
            this.SubCategoryCategoryDropDownLst.Size = new System.Drawing.Size(211, 32);
            this.SubCategoryCategoryDropDownLst.TabIndex = 9;
            this.SubCategoryCategoryDropDownLst.Text = null;
            this.SubCategoryCategoryDropDownLst.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.SubCategoryCategoryDropDownLst.TextLeftMargin = 5;
            // 
            // CategoryDropDownLst
            // 
            this.CategoryDropDownLst.BackColor = System.Drawing.Color.Transparent;
            this.CategoryDropDownLst.BackgroundColor = System.Drawing.Color.White;
            this.CategoryDropDownLst.BorderColor = System.Drawing.Color.Silver;
            this.CategoryDropDownLst.BorderRadius = 1;
            this.CategoryDropDownLst.Color = System.Drawing.Color.Silver;
            this.CategoryDropDownLst.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.CategoryDropDownLst.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.CategoryDropDownLst.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CategoryDropDownLst.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.CategoryDropDownLst.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.CategoryDropDownLst.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.CategoryDropDownLst.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.CategoryDropDownLst.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.CategoryDropDownLst.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.CategoryDropDownLst.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.CategoryDropDownLst.FillDropDown = true;
            this.CategoryDropDownLst.FillIndicator = false;
            this.CategoryDropDownLst.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.CategoryDropDownLst.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.CategoryDropDownLst.ForeColor = System.Drawing.Color.Black;
            this.CategoryDropDownLst.FormattingEnabled = true;
            this.CategoryDropDownLst.Icon = null;
            this.CategoryDropDownLst.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.CategoryDropDownLst.IndicatorColor = System.Drawing.Color.Gray;
            this.CategoryDropDownLst.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.CategoryDropDownLst.ItemBackColor = System.Drawing.Color.White;
            this.CategoryDropDownLst.ItemBorderColor = System.Drawing.Color.White;
            this.CategoryDropDownLst.ItemForeColor = System.Drawing.Color.Black;
            this.CategoryDropDownLst.ItemHeight = 26;
            this.CategoryDropDownLst.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.CategoryDropDownLst.ItemHighLightForeColor = System.Drawing.Color.White;
            this.CategoryDropDownLst.ItemTopMargin = 3;
            this.CategoryDropDownLst.Location = new System.Drawing.Point(636, 80);
            this.CategoryDropDownLst.Name = "CategoryDropDownLst";
            this.CategoryDropDownLst.Size = new System.Drawing.Size(171, 32);
            this.CategoryDropDownLst.TabIndex = 8;
            this.CategoryDropDownLst.Text = null;
            this.CategoryDropDownLst.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.CategoryDropDownLst.TextLeftMargin = 5;
            this.CategoryDropDownLst.SelectedIndexChanged += new System.EventHandler(this.CategoryDropdown_SelectedIndexChanged);
            // 
            // CategoryDropdownLbl
            // 
            this.CategoryDropdownLbl.AutoSize = true;
            this.CategoryDropdownLbl.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.CategoryDropdownLbl.Location = new System.Drawing.Point(553, 89);
            this.CategoryDropdownLbl.Name = "CategoryDropdownLbl";
            this.CategoryDropdownLbl.Size = new System.Drawing.Size(70, 16);
            this.CategoryDropdownLbl.TabIndex = 0;
            this.CategoryDropdownLbl.Text = "Category";
            // 
            // StockQtyLbl
            // 
            this.StockQtyLbl.AutoSize = true;
            this.StockQtyLbl.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.StockQtyLbl.Location = new System.Drawing.Point(361, 92);
            this.StockQtyLbl.Name = "StockQtyLbl";
            this.StockQtyLbl.Size = new System.Drawing.Size(73, 16);
            this.StockQtyLbl.TabIndex = 8;
            this.StockQtyLbl.Text = "Stock Qty";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(906, 34);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(112, 16);
            this.label3.TabIndex = 0;
            this.label3.Text = "Purchase Price";
            // 
            // P_SaleLbl
            // 
            this.P_SaleLbl.AutoSize = true;
            this.P_SaleLbl.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.P_SaleLbl.Location = new System.Drawing.Point(153, 91);
            this.P_SaleLbl.Name = "P_SaleLbl";
            this.P_SaleLbl.Size = new System.Drawing.Size(79, 16);
            this.P_SaleLbl.TabIndex = 0;
            this.P_SaleLbl.Text = "Sale Price";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(361, 34);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(85, 16);
            this.label2.TabIndex = 0;
            this.label2.Text = "Urdu Name";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(9, 34);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(105, 16);
            this.label1.TabIndex = 0;
            this.label1.Text = "Product Name";
            // 
            // ProductListGridGrp
            // 
            this.ProductListGridGrp.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.ProductListGridGrp.BorderColor = System.Drawing.Color.LightGray;
            this.ProductListGridGrp.BorderRadius = 1;
            this.ProductListGridGrp.BorderThickness = 1;
            this.ProductListGridGrp.Controls.Add(this.ProductListGrid);
            this.ProductListGridGrp.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ProductListGridGrp.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ProductListGridGrp.LabelIndent = 10;
            this.ProductListGridGrp.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.ProductListGridGrp.Location = new System.Drawing.Point(15, 288);
            this.ProductListGridGrp.Name = "ProductListGridGrp";
            this.ProductListGridGrp.Size = new System.Drawing.Size(1292, 428);
            this.ProductListGridGrp.TabIndex = 1;
            this.ProductListGridGrp.TabStop = false;
            this.ProductListGridGrp.Text = "Product List";
            // 
            // ProductListGrid
            // 
            this.ProductListGrid.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.ProductListGrid.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.ProductListGrid.Location = new System.Drawing.Point(13, 26);
            this.ProductListGrid.Name = "ProductListGrid";
            this.ProductListGrid.RowHeadersWidth = 51;
            this.ProductListGrid.RowTemplate.Height = 24;
            this.ProductListGrid.Size = new System.Drawing.Size(1262, 396);
            this.ProductListGrid.TabIndex = 0;
            // 
            // p_costTxt
            // 
            this.p_costTxt.AcceptsReturn = false;
            this.p_costTxt.AcceptsTab = false;
            this.p_costTxt.AnimationSpeed = 200;
            this.p_costTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.p_costTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.p_costTxt.BackColor = System.Drawing.Color.Transparent;
            this.p_costTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("p_costTxt.BackgroundImage")));
            this.p_costTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.p_costTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.p_costTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.p_costTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.p_costTxt.BorderRadius = 1;
            this.p_costTxt.BorderThickness = 1;
            this.p_costTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.p_costTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.p_costTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.p_costTxt.DefaultText = "";
            this.p_costTxt.FillColor = System.Drawing.Color.White;
            this.p_costTxt.HideSelection = true;
            this.p_costTxt.IconLeft = null;
            this.p_costTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.p_costTxt.IconPadding = 10;
            this.p_costTxt.IconRight = null;
            this.p_costTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.p_costTxt.Lines = new string[0];
            this.p_costTxt.Location = new System.Drawing.Point(58, 77);
            this.p_costTxt.MaxLength = 32767;
            this.p_costTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.p_costTxt.Modified = false;
            this.p_costTxt.Multiline = false;
            this.p_costTxt.Name = "p_costTxt";
            stateProperties85.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties85.FillColor = System.Drawing.Color.Empty;
            stateProperties85.ForeColor = System.Drawing.Color.Empty;
            stateProperties85.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.p_costTxt.OnActiveState = stateProperties85;
            stateProperties86.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties86.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties86.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties86.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.p_costTxt.OnDisabledState = stateProperties86;
            stateProperties87.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties87.FillColor = System.Drawing.Color.Empty;
            stateProperties87.ForeColor = System.Drawing.Color.Empty;
            stateProperties87.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.p_costTxt.OnHoverState = stateProperties87;
            stateProperties88.BorderColor = System.Drawing.Color.Silver;
            stateProperties88.FillColor = System.Drawing.Color.White;
            stateProperties88.ForeColor = System.Drawing.Color.Empty;
            stateProperties88.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.p_costTxt.OnIdleState = stateProperties88;
            this.p_costTxt.Padding = new System.Windows.Forms.Padding(3);
            this.p_costTxt.PasswordChar = '\0';
            this.p_costTxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.p_costTxt.PlaceholderText = "Cost";
            this.p_costTxt.ReadOnly = false;
            this.p_costTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.p_costTxt.SelectedText = "";
            this.p_costTxt.SelectionLength = 0;
            this.p_costTxt.SelectionStart = 0;
            this.p_costTxt.ShortcutsEnabled = true;
            this.p_costTxt.Size = new System.Drawing.Size(73, 41);
            this.p_costTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.p_costTxt.TabIndex = 5;
            this.p_costTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.p_costTxt.TextMarginBottom = 0;
            this.p_costTxt.TextMarginLeft = 3;
            this.p_costTxt.TextMarginTop = 0;
            this.p_costTxt.TextPlaceholder = "Cost";
            this.p_costTxt.UseSystemPasswordChar = false;
            this.p_costTxt.WordWrap = true;
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "Edit";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges13.BottomLeft = true;
            borderEdges13.BottomRight = true;
            borderEdges13.TopLeft = true;
            borderEdges13.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges13;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton2.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.IdleBorderRadius = 1;
            this.bunifuButton2.IdleBorderThickness = 1;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(984, 134);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 1;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.BorderRadius = 1;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.OnIdleState.BorderRadius = 1;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnIdleState.IconLeftImage = null;
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 1;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(72, 39);
            this.bunifuButton2.TabIndex = 0;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            // 
            // ProductSaveBtn
            // 
            this.ProductSaveBtn.AllowAnimations = true;
            this.ProductSaveBtn.AllowMouseEffects = true;
            this.ProductSaveBtn.AllowToggling = false;
            this.ProductSaveBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.ProductSaveBtn.AnimationSpeed = 200;
            this.ProductSaveBtn.AutoGenerateColors = false;
            this.ProductSaveBtn.AutoRoundBorders = false;
            this.ProductSaveBtn.AutoSizeLeftIcon = true;
            this.ProductSaveBtn.AutoSizeRightIcon = true;
            this.ProductSaveBtn.BackColor = System.Drawing.Color.Transparent;
            this.ProductSaveBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.ProductSaveBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ProductSaveBtn.BackgroundImage")));
            this.ProductSaveBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ProductSaveBtn.ButtonText = "Save";
            this.ProductSaveBtn.ButtonTextMarginLeft = 0;
            this.ProductSaveBtn.ColorContrastOnClick = 45;
            this.ProductSaveBtn.ColorContrastOnHover = 45;
            this.ProductSaveBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges14.BottomLeft = true;
            borderEdges14.BottomRight = true;
            borderEdges14.TopLeft = true;
            borderEdges14.TopRight = true;
            this.ProductSaveBtn.CustomizableEdges = borderEdges14;
            this.ProductSaveBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ProductSaveBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ProductSaveBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ProductSaveBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ProductSaveBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ProductSaveBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ProductSaveBtn.ForeColor = System.Drawing.Color.White;
            this.ProductSaveBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ProductSaveBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ProductSaveBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ProductSaveBtn.IconMarginLeft = 11;
            this.ProductSaveBtn.IconPadding = 10;
            this.ProductSaveBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ProductSaveBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ProductSaveBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ProductSaveBtn.IconSize = 25;
            this.ProductSaveBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.ProductSaveBtn.IdleBorderRadius = 1;
            this.ProductSaveBtn.IdleBorderThickness = 1;
            this.ProductSaveBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.ProductSaveBtn.IdleIconLeftImage = null;
            this.ProductSaveBtn.IdleIconRightImage = null;
            this.ProductSaveBtn.IndicateFocus = false;
            this.ProductSaveBtn.Location = new System.Drawing.Point(1067, 134);
            this.ProductSaveBtn.Name = "ProductSaveBtn";
            this.ProductSaveBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ProductSaveBtn.OnDisabledState.BorderRadius = 1;
            this.ProductSaveBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ProductSaveBtn.OnDisabledState.BorderThickness = 1;
            this.ProductSaveBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ProductSaveBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ProductSaveBtn.OnDisabledState.IconLeftImage = null;
            this.ProductSaveBtn.OnDisabledState.IconRightImage = null;
            this.ProductSaveBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ProductSaveBtn.onHoverState.BorderRadius = 1;
            this.ProductSaveBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ProductSaveBtn.onHoverState.BorderThickness = 1;
            this.ProductSaveBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ProductSaveBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ProductSaveBtn.onHoverState.IconLeftImage = null;
            this.ProductSaveBtn.onHoverState.IconRightImage = null;
            this.ProductSaveBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.ProductSaveBtn.OnIdleState.BorderRadius = 1;
            this.ProductSaveBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ProductSaveBtn.OnIdleState.BorderThickness = 1;
            this.ProductSaveBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.ProductSaveBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.ProductSaveBtn.OnIdleState.IconLeftImage = null;
            this.ProductSaveBtn.OnIdleState.IconRightImage = null;
            this.ProductSaveBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ProductSaveBtn.OnPressedState.BorderRadius = 1;
            this.ProductSaveBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ProductSaveBtn.OnPressedState.BorderThickness = 1;
            this.ProductSaveBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ProductSaveBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ProductSaveBtn.OnPressedState.IconLeftImage = null;
            this.ProductSaveBtn.OnPressedState.IconRightImage = null;
            this.ProductSaveBtn.Size = new System.Drawing.Size(79, 39);
            this.ProductSaveBtn.TabIndex = 10;
            this.ProductSaveBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ProductSaveBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ProductSaveBtn.TextMarginLeft = 0;
            this.ProductSaveBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.ProductSaveBtn.UseDefaultRadiusAndThickness = true;
            this.ProductSaveBtn.Click += new System.EventHandler(this.ProductSaveBtn_Click);
            // 
            // P_StockQtyTxt
            // 
            this.P_StockQtyTxt.AcceptsReturn = false;
            this.P_StockQtyTxt.AcceptsTab = false;
            this.P_StockQtyTxt.AnimationSpeed = 200;
            this.P_StockQtyTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.P_StockQtyTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.P_StockQtyTxt.BackColor = System.Drawing.Color.Transparent;
            this.P_StockQtyTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("P_StockQtyTxt.BackgroundImage")));
            this.P_StockQtyTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.P_StockQtyTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.P_StockQtyTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.P_StockQtyTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.P_StockQtyTxt.BorderRadius = 1;
            this.P_StockQtyTxt.BorderThickness = 1;
            this.P_StockQtyTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.P_StockQtyTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.P_StockQtyTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.P_StockQtyTxt.DefaultText = "";
            this.P_StockQtyTxt.FillColor = System.Drawing.Color.White;
            this.P_StockQtyTxt.HideSelection = true;
            this.P_StockQtyTxt.IconLeft = null;
            this.P_StockQtyTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.P_StockQtyTxt.IconPadding = 10;
            this.P_StockQtyTxt.IconRight = null;
            this.P_StockQtyTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.P_StockQtyTxt.Lines = new string[0];
            this.P_StockQtyTxt.Location = new System.Drawing.Point(450, 78);
            this.P_StockQtyTxt.MaxLength = 32767;
            this.P_StockQtyTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.P_StockQtyTxt.Modified = false;
            this.P_StockQtyTxt.Multiline = false;
            this.P_StockQtyTxt.Name = "P_StockQtyTxt";
            stateProperties89.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties89.FillColor = System.Drawing.Color.Empty;
            stateProperties89.ForeColor = System.Drawing.Color.Empty;
            stateProperties89.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.P_StockQtyTxt.OnActiveState = stateProperties89;
            stateProperties90.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties90.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties90.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties90.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.P_StockQtyTxt.OnDisabledState = stateProperties90;
            stateProperties91.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties91.FillColor = System.Drawing.Color.Empty;
            stateProperties91.ForeColor = System.Drawing.Color.Empty;
            stateProperties91.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.P_StockQtyTxt.OnHoverState = stateProperties91;
            stateProperties92.BorderColor = System.Drawing.Color.Silver;
            stateProperties92.FillColor = System.Drawing.Color.White;
            stateProperties92.ForeColor = System.Drawing.Color.Empty;
            stateProperties92.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.P_StockQtyTxt.OnIdleState = stateProperties92;
            this.P_StockQtyTxt.Padding = new System.Windows.Forms.Padding(3);
            this.P_StockQtyTxt.PasswordChar = '\0';
            this.P_StockQtyTxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.P_StockQtyTxt.PlaceholderText = "Qty";
            this.P_StockQtyTxt.ReadOnly = false;
            this.P_StockQtyTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.P_StockQtyTxt.SelectedText = "";
            this.P_StockQtyTxt.SelectionLength = 0;
            this.P_StockQtyTxt.SelectionStart = 0;
            this.P_StockQtyTxt.ShortcutsEnabled = true;
            this.P_StockQtyTxt.Size = new System.Drawing.Size(69, 41);
            this.P_StockQtyTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.P_StockQtyTxt.TabIndex = 7;
            this.P_StockQtyTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.P_StockQtyTxt.TextMarginBottom = 0;
            this.P_StockQtyTxt.TextMarginLeft = 3;
            this.P_StockQtyTxt.TextMarginTop = 0;
            this.P_StockQtyTxt.TextPlaceholder = "Qty";
            this.P_StockQtyTxt.UseSystemPasswordChar = false;
            this.P_StockQtyTxt.WordWrap = true;
            // 
            // PurchasePriceTxt
            // 
            this.PurchasePriceTxt.AcceptsReturn = false;
            this.PurchasePriceTxt.AcceptsTab = false;
            this.PurchasePriceTxt.AnimationSpeed = 200;
            this.PurchasePriceTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.PurchasePriceTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.PurchasePriceTxt.BackColor = System.Drawing.Color.Transparent;
            this.PurchasePriceTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PurchasePriceTxt.BackgroundImage")));
            this.PurchasePriceTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.PurchasePriceTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PurchasePriceTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PurchasePriceTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.PurchasePriceTxt.BorderRadius = 1;
            this.PurchasePriceTxt.BorderThickness = 1;
            this.PurchasePriceTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.PurchasePriceTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.PurchasePriceTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.PurchasePriceTxt.DefaultText = "";
            this.PurchasePriceTxt.FillColor = System.Drawing.Color.White;
            this.PurchasePriceTxt.HideSelection = true;
            this.PurchasePriceTxt.IconLeft = null;
            this.PurchasePriceTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.PurchasePriceTxt.IconPadding = 10;
            this.PurchasePriceTxt.IconRight = null;
            this.PurchasePriceTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.PurchasePriceTxt.Lines = new string[0];
            this.PurchasePriceTxt.Location = new System.Drawing.Point(1037, 21);
            this.PurchasePriceTxt.MaxLength = 32767;
            this.PurchasePriceTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.PurchasePriceTxt.Modified = false;
            this.PurchasePriceTxt.Multiline = false;
            this.PurchasePriceTxt.Name = "PurchasePriceTxt";
            stateProperties93.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties93.FillColor = System.Drawing.Color.Empty;
            stateProperties93.ForeColor = System.Drawing.Color.Empty;
            stateProperties93.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PurchasePriceTxt.OnActiveState = stateProperties93;
            stateProperties94.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties94.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties94.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties94.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.PurchasePriceTxt.OnDisabledState = stateProperties94;
            stateProperties95.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties95.FillColor = System.Drawing.Color.Empty;
            stateProperties95.ForeColor = System.Drawing.Color.Empty;
            stateProperties95.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PurchasePriceTxt.OnHoverState = stateProperties95;
            stateProperties96.BorderColor = System.Drawing.Color.Silver;
            stateProperties96.FillColor = System.Drawing.Color.White;
            stateProperties96.ForeColor = System.Drawing.Color.Empty;
            stateProperties96.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PurchasePriceTxt.OnIdleState = stateProperties96;
            this.PurchasePriceTxt.Padding = new System.Windows.Forms.Padding(3);
            this.PurchasePriceTxt.PasswordChar = '\0';
            this.PurchasePriceTxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.PurchasePriceTxt.PlaceholderText = "Pruchase";
            this.PurchasePriceTxt.ReadOnly = false;
            this.PurchasePriceTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.PurchasePriceTxt.SelectedText = "";
            this.PurchasePriceTxt.SelectionLength = 0;
            this.PurchasePriceTxt.SelectionStart = 0;
            this.PurchasePriceTxt.ShortcutsEnabled = true;
            this.PurchasePriceTxt.Size = new System.Drawing.Size(102, 41);
            this.PurchasePriceTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.PurchasePriceTxt.TabIndex = 4;
            this.PurchasePriceTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.PurchasePriceTxt.TextMarginBottom = 0;
            this.PurchasePriceTxt.TextMarginLeft = 3;
            this.PurchasePriceTxt.TextMarginTop = 0;
            this.PurchasePriceTxt.TextPlaceholder = "Pruchase";
            this.PurchasePriceTxt.UseSystemPasswordChar = false;
            this.PurchasePriceTxt.WordWrap = true;
            // 
            // P_SalePriceTxt
            // 
            this.P_SalePriceTxt.AcceptsReturn = false;
            this.P_SalePriceTxt.AcceptsTab = false;
            this.P_SalePriceTxt.AnimationSpeed = 200;
            this.P_SalePriceTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.P_SalePriceTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.P_SalePriceTxt.BackColor = System.Drawing.Color.Transparent;
            this.P_SalePriceTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("P_SalePriceTxt.BackgroundImage")));
            this.P_SalePriceTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.P_SalePriceTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.P_SalePriceTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.P_SalePriceTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.P_SalePriceTxt.BorderRadius = 1;
            this.P_SalePriceTxt.BorderThickness = 1;
            this.P_SalePriceTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.P_SalePriceTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.P_SalePriceTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.P_SalePriceTxt.DefaultText = "";
            this.P_SalePriceTxt.FillColor = System.Drawing.Color.White;
            this.P_SalePriceTxt.HideSelection = true;
            this.P_SalePriceTxt.IconLeft = null;
            this.P_SalePriceTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.P_SalePriceTxt.IconPadding = 10;
            this.P_SalePriceTxt.IconRight = null;
            this.P_SalePriceTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.P_SalePriceTxt.Lines = new string[0];
            this.P_SalePriceTxt.Location = new System.Drawing.Point(281, 78);
            this.P_SalePriceTxt.MaxLength = 32767;
            this.P_SalePriceTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.P_SalePriceTxt.Modified = false;
            this.P_SalePriceTxt.Multiline = false;
            this.P_SalePriceTxt.Name = "P_SalePriceTxt";
            stateProperties97.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties97.FillColor = System.Drawing.Color.Empty;
            stateProperties97.ForeColor = System.Drawing.Color.Empty;
            stateProperties97.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.P_SalePriceTxt.OnActiveState = stateProperties97;
            stateProperties98.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties98.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties98.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties98.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.P_SalePriceTxt.OnDisabledState = stateProperties98;
            stateProperties99.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties99.FillColor = System.Drawing.Color.Empty;
            stateProperties99.ForeColor = System.Drawing.Color.Empty;
            stateProperties99.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.P_SalePriceTxt.OnHoverState = stateProperties99;
            stateProperties100.BorderColor = System.Drawing.Color.Silver;
            stateProperties100.FillColor = System.Drawing.Color.White;
            stateProperties100.ForeColor = System.Drawing.Color.Empty;
            stateProperties100.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.P_SalePriceTxt.OnIdleState = stateProperties100;
            this.P_SalePriceTxt.Padding = new System.Windows.Forms.Padding(3);
            this.P_SalePriceTxt.PasswordChar = '\0';
            this.P_SalePriceTxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.P_SalePriceTxt.PlaceholderText = "Sale";
            this.P_SalePriceTxt.ReadOnly = false;
            this.P_SalePriceTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.P_SalePriceTxt.SelectedText = "";
            this.P_SalePriceTxt.SelectionLength = 0;
            this.P_SalePriceTxt.SelectionStart = 0;
            this.P_SalePriceTxt.ShortcutsEnabled = true;
            this.P_SalePriceTxt.Size = new System.Drawing.Size(73, 41);
            this.P_SalePriceTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.P_SalePriceTxt.TabIndex = 6;
            this.P_SalePriceTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.P_SalePriceTxt.TextMarginBottom = 0;
            this.P_SalePriceTxt.TextMarginLeft = 3;
            this.P_SalePriceTxt.TextMarginTop = 0;
            this.P_SalePriceTxt.TextPlaceholder = "Sale";
            this.P_SalePriceTxt.UseSystemPasswordChar = false;
            this.P_SalePriceTxt.WordWrap = true;
            // 
            // ProductUrduNameTxt
            // 
            this.ProductUrduNameTxt.AcceptsReturn = false;
            this.ProductUrduNameTxt.AcceptsTab = false;
            this.ProductUrduNameTxt.AnimationSpeed = 200;
            this.ProductUrduNameTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ProductUrduNameTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ProductUrduNameTxt.BackColor = System.Drawing.Color.Transparent;
            this.ProductUrduNameTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ProductUrduNameTxt.BackgroundImage")));
            this.ProductUrduNameTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ProductUrduNameTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ProductUrduNameTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ProductUrduNameTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.ProductUrduNameTxt.BorderRadius = 1;
            this.ProductUrduNameTxt.BorderThickness = 1;
            this.ProductUrduNameTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ProductUrduNameTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ProductUrduNameTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.ProductUrduNameTxt.DefaultText = "";
            this.ProductUrduNameTxt.FillColor = System.Drawing.Color.White;
            this.ProductUrduNameTxt.HideSelection = true;
            this.ProductUrduNameTxt.IconLeft = null;
            this.ProductUrduNameTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ProductUrduNameTxt.IconPadding = 10;
            this.ProductUrduNameTxt.IconRight = null;
            this.ProductUrduNameTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ProductUrduNameTxt.Lines = new string[0];
            this.ProductUrduNameTxt.Location = new System.Drawing.Point(452, 22);
            this.ProductUrduNameTxt.MaxLength = 32767;
            this.ProductUrduNameTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.ProductUrduNameTxt.Modified = false;
            this.ProductUrduNameTxt.Multiline = false;
            this.ProductUrduNameTxt.Name = "ProductUrduNameTxt";
            stateProperties101.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties101.FillColor = System.Drawing.Color.Empty;
            stateProperties101.ForeColor = System.Drawing.Color.Empty;
            stateProperties101.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ProductUrduNameTxt.OnActiveState = stateProperties101;
            stateProperties102.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties102.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties102.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties102.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ProductUrduNameTxt.OnDisabledState = stateProperties102;
            stateProperties103.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties103.FillColor = System.Drawing.Color.Empty;
            stateProperties103.ForeColor = System.Drawing.Color.Empty;
            stateProperties103.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ProductUrduNameTxt.OnHoverState = stateProperties103;
            stateProperties104.BorderColor = System.Drawing.Color.Silver;
            stateProperties104.FillColor = System.Drawing.Color.White;
            stateProperties104.ForeColor = System.Drawing.Color.Empty;
            stateProperties104.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ProductUrduNameTxt.OnIdleState = stateProperties104;
            this.ProductUrduNameTxt.Padding = new System.Windows.Forms.Padding(3);
            this.ProductUrduNameTxt.PasswordChar = '\0';
            this.ProductUrduNameTxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.ProductUrduNameTxt.PlaceholderText = "Urdu Name";
            this.ProductUrduNameTxt.ReadOnly = false;
            this.ProductUrduNameTxt.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.ProductUrduNameTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ProductUrduNameTxt.SelectedText = "";
            this.ProductUrduNameTxt.SelectionLength = 0;
            this.ProductUrduNameTxt.SelectionStart = 0;
            this.ProductUrduNameTxt.ShortcutsEnabled = true;
            this.ProductUrduNameTxt.Size = new System.Drawing.Size(248, 41);
            this.ProductUrduNameTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ProductUrduNameTxt.TabIndex = 2;
            this.ProductUrduNameTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ProductUrduNameTxt.TextMarginBottom = 0;
            this.ProductUrduNameTxt.TextMarginLeft = 3;
            this.ProductUrduNameTxt.TextMarginTop = 0;
            this.ProductUrduNameTxt.TextPlaceholder = "Urdu Name";
            this.ProductUrduNameTxt.UseSystemPasswordChar = false;
            this.ProductUrduNameTxt.WordWrap = true;
            // 
            // ProductEngNameTxt
            // 
            this.ProductEngNameTxt.AcceptsReturn = false;
            this.ProductEngNameTxt.AcceptsTab = false;
            this.ProductEngNameTxt.AnimationSpeed = 200;
            this.ProductEngNameTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ProductEngNameTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ProductEngNameTxt.BackColor = System.Drawing.Color.Transparent;
            this.ProductEngNameTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ProductEngNameTxt.BackgroundImage")));
            this.ProductEngNameTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ProductEngNameTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ProductEngNameTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ProductEngNameTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.ProductEngNameTxt.BorderRadius = 1;
            this.ProductEngNameTxt.BorderThickness = 1;
            this.ProductEngNameTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ProductEngNameTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ProductEngNameTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.ProductEngNameTxt.DefaultText = "";
            this.ProductEngNameTxt.FillColor = System.Drawing.Color.White;
            this.ProductEngNameTxt.HideSelection = true;
            this.ProductEngNameTxt.IconLeft = null;
            this.ProductEngNameTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ProductEngNameTxt.IconPadding = 10;
            this.ProductEngNameTxt.IconRight = null;
            this.ProductEngNameTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ProductEngNameTxt.Lines = new string[0];
            this.ProductEngNameTxt.Location = new System.Drawing.Point(124, 22);
            this.ProductEngNameTxt.MaxLength = 32767;
            this.ProductEngNameTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.ProductEngNameTxt.Modified = false;
            this.ProductEngNameTxt.Multiline = false;
            this.ProductEngNameTxt.Name = "ProductEngNameTxt";
            stateProperties105.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties105.FillColor = System.Drawing.Color.Empty;
            stateProperties105.ForeColor = System.Drawing.Color.Empty;
            stateProperties105.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ProductEngNameTxt.OnActiveState = stateProperties105;
            stateProperties106.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties106.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties106.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties106.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ProductEngNameTxt.OnDisabledState = stateProperties106;
            stateProperties107.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties107.FillColor = System.Drawing.Color.Empty;
            stateProperties107.ForeColor = System.Drawing.Color.Empty;
            stateProperties107.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ProductEngNameTxt.OnHoverState = stateProperties107;
            stateProperties108.BorderColor = System.Drawing.Color.Silver;
            stateProperties108.FillColor = System.Drawing.Color.White;
            stateProperties108.ForeColor = System.Drawing.Color.Empty;
            stateProperties108.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ProductEngNameTxt.OnIdleState = stateProperties108;
            this.ProductEngNameTxt.Padding = new System.Windows.Forms.Padding(3);
            this.ProductEngNameTxt.PasswordChar = '\0';
            this.ProductEngNameTxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.ProductEngNameTxt.PlaceholderText = "Product Name";
            this.ProductEngNameTxt.ReadOnly = false;
            this.ProductEngNameTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ProductEngNameTxt.SelectedText = "";
            this.ProductEngNameTxt.SelectionLength = 0;
            this.ProductEngNameTxt.SelectionStart = 0;
            this.ProductEngNameTxt.ShortcutsEnabled = true;
            this.ProductEngNameTxt.Size = new System.Drawing.Size(227, 41);
            this.ProductEngNameTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ProductEngNameTxt.TabIndex = 1;
            this.ProductEngNameTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ProductEngNameTxt.TextMarginBottom = 0;
            this.ProductEngNameTxt.TextMarginLeft = 3;
            this.ProductEngNameTxt.TextMarginTop = 0;
            this.ProductEngNameTxt.TextPlaceholder = "Product Name";
            this.ProductEngNameTxt.UseSystemPasswordChar = false;
            this.ProductEngNameTxt.WordWrap = true;
            // 
            // ProdSearchTxt
            // 
            this.ProdSearchTxt.AcceptsReturn = false;
            this.ProdSearchTxt.AcceptsTab = false;
            this.ProdSearchTxt.AnimationSpeed = 200;
            this.ProdSearchTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ProdSearchTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ProdSearchTxt.BackColor = System.Drawing.Color.Transparent;
            this.ProdSearchTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ProdSearchTxt.BackgroundImage")));
            this.ProdSearchTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ProdSearchTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ProdSearchTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ProdSearchTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.ProdSearchTxt.BorderRadius = 1;
            this.ProdSearchTxt.BorderThickness = 1;
            this.ProdSearchTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ProdSearchTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ProdSearchTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.ProdSearchTxt.DefaultText = "";
            this.ProdSearchTxt.FillColor = System.Drawing.Color.White;
            this.ProdSearchTxt.HideSelection = true;
            this.ProdSearchTxt.IconLeft = null;
            this.ProdSearchTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ProdSearchTxt.IconPadding = 10;
            this.ProdSearchTxt.IconRight = null;
            this.ProdSearchTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ProdSearchTxt.Lines = new string[0];
            this.ProdSearchTxt.Location = new System.Drawing.Point(15, 244);
            this.ProdSearchTxt.MaxLength = 32767;
            this.ProdSearchTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.ProdSearchTxt.Modified = false;
            this.ProdSearchTxt.Multiline = false;
            this.ProdSearchTxt.Name = "ProdSearchTxt";
            stateProperties109.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties109.FillColor = System.Drawing.Color.Empty;
            stateProperties109.ForeColor = System.Drawing.Color.Empty;
            stateProperties109.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ProdSearchTxt.OnActiveState = stateProperties109;
            stateProperties110.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties110.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties110.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties110.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ProdSearchTxt.OnDisabledState = stateProperties110;
            stateProperties111.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties111.FillColor = System.Drawing.Color.Empty;
            stateProperties111.ForeColor = System.Drawing.Color.Empty;
            stateProperties111.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ProdSearchTxt.OnHoverState = stateProperties111;
            stateProperties112.BorderColor = System.Drawing.Color.Silver;
            stateProperties112.FillColor = System.Drawing.Color.White;
            stateProperties112.ForeColor = System.Drawing.Color.Empty;
            stateProperties112.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ProdSearchTxt.OnIdleState = stateProperties112;
            this.ProdSearchTxt.Padding = new System.Windows.Forms.Padding(3);
            this.ProdSearchTxt.PasswordChar = '\0';
            this.ProdSearchTxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.ProdSearchTxt.PlaceholderText = "Search...";
            this.ProdSearchTxt.ReadOnly = false;
            this.ProdSearchTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ProdSearchTxt.SelectedText = "";
            this.ProdSearchTxt.SelectionLength = 0;
            this.ProdSearchTxt.SelectionStart = 0;
            this.ProdSearchTxt.ShortcutsEnabled = true;
            this.ProdSearchTxt.Size = new System.Drawing.Size(519, 41);
            this.ProdSearchTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ProdSearchTxt.TabIndex = 2;
            this.ProdSearchTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ProdSearchTxt.TextMarginBottom = 0;
            this.ProdSearchTxt.TextMarginLeft = 3;
            this.ProdSearchTxt.TextMarginTop = 0;
            this.ProdSearchTxt.TextPlaceholder = "Search...";
            this.ProdSearchTxt.UseSystemPasswordChar = false;
            this.ProdSearchTxt.WordWrap = true;
            this.ProdSearchTxt.TextChange += new System.EventHandler(this.ProdSearchTxt_TextChanged);
            // 
            // NextBtn
            // 
            this.NextBtn.AllowAnimations = true;
            this.NextBtn.AllowMouseEffects = true;
            this.NextBtn.AllowToggling = false;
            this.NextBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.NextBtn.AnimationSpeed = 200;
            this.NextBtn.AutoGenerateColors = false;
            this.NextBtn.AutoRoundBorders = false;
            this.NextBtn.AutoSizeLeftIcon = true;
            this.NextBtn.AutoSizeRightIcon = true;
            this.NextBtn.BackColor = System.Drawing.Color.Transparent;
            this.NextBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.NextBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("NextBtn.BackgroundImage")));
            this.NextBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NextBtn.ButtonText = "Next";
            this.NextBtn.ButtonTextMarginLeft = 0;
            this.NextBtn.ColorContrastOnClick = 45;
            this.NextBtn.ColorContrastOnHover = 45;
            this.NextBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges15.BottomLeft = true;
            borderEdges15.BottomRight = true;
            borderEdges15.TopLeft = true;
            borderEdges15.TopRight = true;
            this.NextBtn.CustomizableEdges = borderEdges15;
            this.NextBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.NextBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.NextBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.NextBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.NextBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.NextBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.NextBtn.ForeColor = System.Drawing.Color.White;
            this.NextBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.NextBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.NextBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.NextBtn.IconMarginLeft = 11;
            this.NextBtn.IconPadding = 10;
            this.NextBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.NextBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.NextBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.NextBtn.IconSize = 25;
            this.NextBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.NextBtn.IdleBorderRadius = 1;
            this.NextBtn.IdleBorderThickness = 1;
            this.NextBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.NextBtn.IdleIconLeftImage = null;
            this.NextBtn.IdleIconRightImage = null;
            this.NextBtn.IndicateFocus = false;
            this.NextBtn.Location = new System.Drawing.Point(1182, 250);
            this.NextBtn.Name = "NextBtn";
            this.NextBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.NextBtn.OnDisabledState.BorderRadius = 1;
            this.NextBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NextBtn.OnDisabledState.BorderThickness = 1;
            this.NextBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.NextBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.NextBtn.OnDisabledState.IconLeftImage = null;
            this.NextBtn.OnDisabledState.IconRightImage = null;
            this.NextBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.NextBtn.onHoverState.BorderRadius = 1;
            this.NextBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NextBtn.onHoverState.BorderThickness = 1;
            this.NextBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.NextBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.NextBtn.onHoverState.IconLeftImage = null;
            this.NextBtn.onHoverState.IconRightImage = null;
            this.NextBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.NextBtn.OnIdleState.BorderRadius = 1;
            this.NextBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NextBtn.OnIdleState.BorderThickness = 1;
            this.NextBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.NextBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.NextBtn.OnIdleState.IconLeftImage = null;
            this.NextBtn.OnIdleState.IconRightImage = null;
            this.NextBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.NextBtn.OnPressedState.BorderRadius = 1;
            this.NextBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NextBtn.OnPressedState.BorderThickness = 1;
            this.NextBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.NextBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.NextBtn.OnPressedState.IconLeftImage = null;
            this.NextBtn.OnPressedState.IconRightImage = null;
            this.NextBtn.Size = new System.Drawing.Size(58, 39);
            this.NextBtn.TabIndex = 16;
            this.NextBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.NextBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.NextBtn.TextMarginLeft = 0;
            this.NextBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.NextBtn.UseDefaultRadiusAndThickness = true;
            this.NextBtn.Click += new System.EventHandler(this.NextBtn_Click);
            // 
            // PrevBtn
            // 
            this.PrevBtn.AllowAnimations = true;
            this.PrevBtn.AllowMouseEffects = true;
            this.PrevBtn.AllowToggling = false;
            this.PrevBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.PrevBtn.AnimationSpeed = 200;
            this.PrevBtn.AutoGenerateColors = false;
            this.PrevBtn.AutoRoundBorders = false;
            this.PrevBtn.AutoSizeLeftIcon = true;
            this.PrevBtn.AutoSizeRightIcon = true;
            this.PrevBtn.BackColor = System.Drawing.Color.Transparent;
            this.PrevBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.PrevBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PrevBtn.BackgroundImage")));
            this.PrevBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PrevBtn.ButtonText = "Prev";
            this.PrevBtn.ButtonTextMarginLeft = 0;
            this.PrevBtn.ColorContrastOnClick = 45;
            this.PrevBtn.ColorContrastOnHover = 45;
            this.PrevBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges16.BottomLeft = true;
            borderEdges16.BottomRight = true;
            borderEdges16.TopLeft = true;
            borderEdges16.TopRight = true;
            this.PrevBtn.CustomizableEdges = borderEdges16;
            this.PrevBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.PrevBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.PrevBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PrevBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.PrevBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.PrevBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.PrevBtn.ForeColor = System.Drawing.Color.White;
            this.PrevBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.PrevBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.PrevBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.PrevBtn.IconMarginLeft = 11;
            this.PrevBtn.IconPadding = 10;
            this.PrevBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.PrevBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.PrevBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.PrevBtn.IconSize = 25;
            this.PrevBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.PrevBtn.IdleBorderRadius = 1;
            this.PrevBtn.IdleBorderThickness = 1;
            this.PrevBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.PrevBtn.IdleIconLeftImage = null;
            this.PrevBtn.IdleIconRightImage = null;
            this.PrevBtn.IndicateFocus = false;
            this.PrevBtn.Location = new System.Drawing.Point(1113, 250);
            this.PrevBtn.Name = "PrevBtn";
            this.PrevBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.PrevBtn.OnDisabledState.BorderRadius = 1;
            this.PrevBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PrevBtn.OnDisabledState.BorderThickness = 1;
            this.PrevBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PrevBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.PrevBtn.OnDisabledState.IconLeftImage = null;
            this.PrevBtn.OnDisabledState.IconRightImage = null;
            this.PrevBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PrevBtn.onHoverState.BorderRadius = 1;
            this.PrevBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PrevBtn.onHoverState.BorderThickness = 1;
            this.PrevBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PrevBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.PrevBtn.onHoverState.IconLeftImage = null;
            this.PrevBtn.onHoverState.IconRightImage = null;
            this.PrevBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.PrevBtn.OnIdleState.BorderRadius = 1;
            this.PrevBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PrevBtn.OnIdleState.BorderThickness = 1;
            this.PrevBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.PrevBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.PrevBtn.OnIdleState.IconLeftImage = null;
            this.PrevBtn.OnIdleState.IconRightImage = null;
            this.PrevBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.PrevBtn.OnPressedState.BorderRadius = 1;
            this.PrevBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PrevBtn.OnPressedState.BorderThickness = 1;
            this.PrevBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.PrevBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.PrevBtn.OnPressedState.IconLeftImage = null;
            this.PrevBtn.OnPressedState.IconRightImage = null;
            this.PrevBtn.Size = new System.Drawing.Size(63, 39);
            this.PrevBtn.TabIndex = 15;
            this.PrevBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.PrevBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.PrevBtn.TextMarginLeft = 0;
            this.PrevBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.PrevBtn.UseDefaultRadiusAndThickness = true;
            this.PrevBtn.Click += new System.EventHandler(this.PrevBtn_Click);
            // 
            // lblStatus
            // 
            this.lblStatus.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.lblStatus.AutoSize = true;
            this.lblStatus.Location = new System.Drawing.Point(844, 269);
            this.lblStatus.Name = "lblStatus";
            this.lblStatus.Size = new System.Drawing.Size(44, 16);
            this.lblStatus.TabIndex = 17;
            this.lblStatus.Text = "Status";
            // 
            // ProductFromControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.lblStatus);
            this.Controls.Add(this.NextBtn);
            this.Controls.Add(this.PrevBtn);
            this.Controls.Add(this.ProdSearchTxt);
            this.Controls.Add(this.ProductListGridGrp);
            this.Controls.Add(this.ProductFromGrp);
            this.Name = "ProductFromControl";
            this.Size = new System.Drawing.Size(1337, 735);
            this.ProductFromGrp.ResumeLayout(false);
            this.ProductFromGrp.PerformLayout();
            this.ProductListGridGrp.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ProductListGrid)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.GroupBox ProductFromGrp;
        private Bunifu.UI.WinForms.BunifuTextBox P_SalePriceTxt;
        private Bunifu.UI.WinForms.BunifuTextBox ProductUrduNameTxt;
        private Bunifu.UI.WinForms.BunifuTextBox ProductEngNameTxt;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private System.ComponentModel.BackgroundWorker backgroundWorker1;
        private System.Windows.Forms.Label P_SaleLbl;
        private System.Windows.Forms.Label CategoryDropdownLbl;
        private Bunifu.UI.WinForms.BunifuTextBox P_StockQtyTxt;
        private System.Windows.Forms.Label StockQtyLbl;
        private Bunifu.UI.WinForms.BunifuTextBox PurchasePriceTxt;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuDropdown SubCategoryCategoryDropDownLst;
        private Bunifu.UI.WinForms.BunifuDropdown CategoryDropDownLst;
        private System.Windows.Forms.Label label4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ProductSaveBtn;
        private System.ComponentModel.BackgroundWorker backgroundWorker2;
        private Bunifu.UI.WinForms.BunifuGroupBox ProductListGridGrp;
        private System.Windows.Forms.Label P_costLbl;
        private Bunifu.UI.WinForms.BunifuTextBox p_costTxt;
        private System.Windows.Forms.Label P_typeLbl;
        private Bunifu.UI.WinForms.BunifuDropdown productTypeDropdown;
        private System.Windows.Forms.DataGridView ProductListGrid;
        private Bunifu.UI.WinForms.BunifuTextBox ProdSearchTxt;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton NextBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton PrevBtn;
        private System.Windows.Forms.Label lblStatus;
    }
}
